In [1]:
!nvidia-smi

[HAMI-core Msg(368:140410801006400:libvgpu.c:839)]: Initializing.....
Fri Aug 14 14:30:20 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L40S                    On  |   00000000:45:00.0 Off |                    0 |
| N/A   28C    P8             35W /  350W |       0MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
[HAMI-core Msg(368:140410801006400:multiprocess_memory_limit.c:455)]: Calling exit handler 368

In [1]:
import gc
import json
import random
import time
from pathlib import Path

import pandas as pd
import torch

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
)

from peft import PeftModel

[HAMI-core Msg(176:140367156518208:libvgpu.c:839)]: Initializing.....

In [2]:
# ============================================================
# PROJECT PATHS
# ============================================================

from pathlib import Path
import random
import torch
import pandas as pd

PROJECT_DIR = Path(
    "/home/jovyan/project work/data_analyssis/fine tuning"
)

BASE_MODEL_ID = "mistralai/Mistral-7B-Instruct-v0.2"

ADAPTER_DIR = (
    PROJECT_DIR
    / "outputs"
    / "mistral_qlora"
    / "final_adapter"
)

TRAIN_DATA_PATH = (
    PROJECT_DIR
    / "outputs"
    / "cleaned_ruhsold_train.csv"
)

# ============================================================
# SYNTHETIC GENERATION OUTPUT DIRECTORIES
# ============================================================

GENERATION_DIR = (
    PROJECT_DIR
    / "outputs"
    / "synthetic_generation"
)

# Small pilot generations used to test prompting and QC
PILOT_OUTPUT_DIR = (
    GENERATION_DIR
    / "pilot"
)

# Final production generations used for augmentation
FULL_OUTPUT_DIR = (
    GENERATION_DIR
    / "full"
)

PILOT_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

FULL_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ============================================================
# FINAL PRODUCTION SETTINGS
# ============================================================

PRODUCTION_BATCH_SIZE = 200

# ============================================================
# VERIFY PATHS
# ============================================================

print("Project directory:", PROJECT_DIR)
print("Adapter exists:", ADAPTER_DIR.exists())
print("Training data exists:", TRAIN_DATA_PATH.exists())
print("Pilot output:", PILOT_OUTPUT_DIR)
print("Full production output:", FULL_OUTPUT_DIR)
print("Production batch size:", PRODUCTION_BATCH_SIZE)

Project directory: /home/jovyan/project work/data_analyssis/fine tuning
Adapter exists: True
Training data exists: True
Pilot output: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/pilot
Full production output: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full
Production batch size: 200

In [3]:
# ============================================================
# REPRODUCIBILITY
# ============================================================

GLOBAL_SEED = 42

random.seed(GLOBAL_SEED)
torch.manual_seed(GLOBAL_SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(GLOBAL_SEED)


# ============================================================
# FINAL 1x AUGMENTATION CONFIGURATION
# ============================================================

AUGMENTATION_CLASSES = [2, 3, 4]

CLASS_FILE_NAMES = {
    2: "religious_hate",
    3: "sexism",
    4: "profane",
}

# Required number of accepted synthetic examples
# after the complete QC pipeline.
ACCEPTED_TARGETS = {
    2: 500,
    3: 537,
    4: 411,
}

# Four authentic same-class demonstrations
# are used for every generation.
N_DEMONSTRATIONS = 4

# Deterministic seed bases.
BASE_GENERATION_SEED = 1000
BASE_DEMONSTRATION_SEED = 5000

print("Final 1x accepted synthetic targets:")

for class_id, target in ACCEPTED_TARGETS.items():
    print(
        f"Class {class_id}: {target}"
    )

print(
    "\nTotal accepted target:",
    sum(ACCEPTED_TARGETS.values())
)

Final 1x accepted synthetic targets:
Class 2: 500
Class 3: 537
Class 4: 411

Total accepted target: 1448

[HAMI-core Msg(176:140367156518208:libvgpu.c:855)]: Initialized

In [4]:
train_df = pd.read_csv(TRAIN_DATA_PATH)

print("Training data shape:", train_df.shape)
print("Columns:", train_df.columns.tolist())

train_df.head()

Training data shape: (6401, 2)
Columns: ['text', 'label']

                                                text  label
0  kia howa hai aap ko allah bless and protect yo...      1
1                                         randdi hai      3
2                              smjh to agai thi mjhy      1
3  haan yrr tuny sahi thukayi ki abhi tak lund da...      3
4              rundi ka bacha bharwaaa ptm ka kuttaa      0

In [5]:
# ============================================================
# PREPARE AUTHENTIC DEMONSTRATION POOL
# ============================================================

def prepare_demonstration_pool(
    dataframe,
    text_column="text",
    label_column="label",
):
    required_columns = {
        text_column,
        label_column,
    }

    missing_columns = (
        required_columns.difference(
            dataframe.columns
        )
    )

    if missing_columns:
        raise ValueError(
            f"Missing required columns: "
            f"{sorted(missing_columns)}"
        )

    clean_df = dataframe[
        [text_column, label_column]
    ].copy()

    clean_df[text_column] = (
        clean_df[text_column]
        .fillna("")
        .astype(str)
        .str.strip()
    )

    clean_df[label_column] = (
        pd.to_numeric(
            clean_df[label_column],
            errors="coerce",
        )
    )

    clean_df = clean_df[
        clean_df[text_column].ne("")
        &
        clean_df[label_column].notna()
    ].copy()

    clean_df[label_column] = (
        clean_df[label_column]
        .astype(int)
    )

    # One copy of each authentic text per class.
    clean_df = (
        clean_df
        .drop_duplicates(
            subset=[
                text_column,
                label_column,
            ]
        )
        .reset_index(drop=True)
    )

    return clean_df


demonstration_pool = (
    prepare_demonstration_pool(
        train_df
    )
)

print(
    "Clean demonstration pool:",
    demonstration_pool.shape
)

print("\nClass distribution:")

print(
    demonstration_pool["label"]
    .value_counts()
    .sort_index()
)

Clean demonstration pool: (6401, 2)

Class distribution:
label
0    1534
1    3422
2     500
3     535
4     410
Name: count, dtype: int64

In [7]:
# ============================================================
# Display original RUHSOLD Sexism examples
# ============================================================

sexism_examples = (
    demonstration_pool[
        demonstration_pool["label"] == 3
    ][["text", "label"]]
    .drop_duplicates(subset=["text"])
    .sample(
        n=10,
        random_state=42
    )
    .reset_index(drop=True)
)

pd.set_option("display.max_colwidth", None)

for i, row in sexism_examples.iterrows():
    print("=" * 80)
    print(f"Example {i+1}")
    print("=" * 80)
    print(row["text"])
    print()

================================================================================
Example 1
================================================================================
gashti orat tujhy koi amreci ni mila abi tak jo teri garmi ko thik kry kise gashti maa ki baiti,

================================================================================
Example 2
================================================================================
yar is pagal ko dafa karo islam ko badnam kr rahi ha randi kahin ki.ak video men nangi ho jati or agli video men hajan ban jati ha

================================================================================
Example 3
================================================================================
sir gazhi hijra hy ap bhe dp laga lein pta tu chly ap  kya cheez ho

================================================================================
Example 4
================================================================================
bc nasal ki randi

================================================================================
Example 5
================================================================================
to be na randi hy na asle....shame on u

================================================================================
Example 6
================================================================================
abu se bhai jaan se chacha jaan sabhi se to halala krwa leti hai begum  or ye tera jeeja ravish khan usse bhi  salon humse akele he kar denge

================================================================================
Example 7
================================================================================
#rashamidesai tu randi moti apni maa ko bech chuki hai ...kisi aur ke hatho..to apni awkat ne rah kar game plan kar ...arhan to vaduaa hai...ram mandir ban rha hai na..but tu chud rahi hai kisi aur ka bister garam kar rhi hai

================================================================================
Example 8
================================================================================
randi tere khene se koch nahi hoga kanjar nasal ki payedawar

================================================================================
Example 9
================================================================================
yeh dekh chakki union ki randi

================================================================================
Example 10
================================================================================
zartaj gul tu mera lora chup ghastiyan lully khanay wali ghashti imran niazi ka lun muh mein leti hai phudi on ki teri maa ko lun maru ghashti .....teri phudi mein pta nai kitny waray vy hein check kr zra... gandi phudi

In [8]:
tokenizer = AutoTokenizer.from_pretrained(
    ADAPTER_DIR,
    use_fast=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "left"

print("Tokenizer loaded")
print("Pad token:", tokenizer.pad_token)
print("EOS token:", tokenizer.eos_token)

Tokenizer loaded
Pad token: </s>
EOS token: </s>

In [9]:
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

print("4-bit quantization configured")

4-bit quantization configured

In [10]:
base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL_ID,
    quantization_config=quantization_config,
    device_map="auto",
    torch_dtype=torch.bfloat16,
)

base_model.config.use_cache = True

print("Base model loaded")
print("Model device:", next(base_model.parameters()).device)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Base model loaded
Model device: cuda:0

In [11]:
finetuned_model = PeftModel.from_pretrained( base_model, ADAPTER_DIR, is_trainable=False, )
finetuned_model.eval()
print("Fine-tuned model loaded")
print("Active adapter:", finetuned_model.active_adapter)

Fine-tuned model loaded
Active adapter: default

In [12]:
# ============================================================
# FINAL PRODUCTION DEMONSTRATION SAMPLER
# ============================================================

def sample_demonstrations(
    dataframe,
    class_id,
    n_examples=4,
    random_state=42,
    text_column="text",
    label_column="label",
):
    """
    Sample unique authentic RUHSOLD demonstrations
    from the requested target class.

    A deterministic random seed is used so that the
    demonstration selection is reproducible.
    """

    # Select authentic examples belonging to the target class.
    class_pool = (
        dataframe[
            dataframe[label_column] == class_id
        ][text_column]
        .fillna("")
        .astype(str)
        .str.strip()
    )

    # Remove empty and duplicate texts.
    class_pool = (
        class_pool[
            class_pool.ne("")
        ]
        .drop_duplicates()
        .reset_index(drop=True)
    )

    if len(class_pool) < n_examples:
        raise ValueError(
            f"Class {class_id} contains only "
            f"{len(class_pool)} unique usable examples, "
            f"but {n_examples} were requested."
        )

    demonstrations = (
        class_pool
        .sample(
            n=n_examples,
            replace=False,
            random_state=random_state,
        )
        .tolist()
    )

    # Final safety check.
    if len(demonstrations) != len(set(demonstrations)):
        raise RuntimeError(
            "Duplicate demonstrations detected."
        )

    return demonstrations

In [13]:
# ============================================================
# RUHSOLD CLASS METADATA
# ============================================================

PROMPT_VERSION = "v3_original_demo_boundary_prompt"

CLASS_METADATA = {
    0: {
        "label": "Abusive/Offensive",

        "definition": (
            "Profane, strongly impolite, rude, or vulgar language used to insult "
            "or hurt a targeted individual or group."
        ),

        "boundary": (
            "The language must have a clear target. If the attack is mainly based "
            "on religion or gender, it belongs to Religious Hate or Sexism. "
            "Vulgar language without an intended target belongs to Profane."
        ),
    },

    1: {
        "label": "Normal",

        "definition": (
            "Text that does not belong to the Abusive/Offensive, Sexism, "
            "Religious Hate, or Profane categories."
        ),

        "boundary": (
            "The post must not contain targeted abuse, gender-based hatred, "
            "religious hatred, or vulgar language."
        ),
    },

    2: {
        "label": "Religious Hate",

        "definition": (
            "Language expressing hatred towards a targeted individual or group "
            "because of religious beliefs, lack of religious beliefs, or religious "
            "identity. It may also use religion to encourage hatred or violence."
        ),

        "boundary": (
            "Religion must be the main reason for the hostility. General political "
            "criticism, personal abuse, or profanity without a clear religious "
            "motivation is not Religious Hate."
        ),
    },

    3: {
        "label": "Sexism",

        "definition": (
            "Language expressing hatred towards a targeted individual or group "
            "because of gender or sexual orientation."
        ),

        "boundary": (
            "Gender or sexual orientation must be the main reason for the hostility. "
            "General insults, sexual vulgarity, or references to female relatives "
            "without gender-based hatred are not Sexism."
        ),
    },

    4: {
        "label": "Profane",

        "definition": (
            "The use of vulgar, foul, or obscene language without an intended target."
        ),

        "boundary": (
            "The profanity should not be directed at a specific person or group. "
            "Targeted insults belong to Abusive/Offensive, while religion-based "
            "or gender-based attacks belong to their respective classes."
        ),
    },
}

print("Prompt version:", PROMPT_VERSION)
print("Class metadata loaded successfully.\n")

for class_id, class_info in CLASS_METADATA.items():
    print(
        f"{class_id}: "
        f"{class_info['label']}"
    )

Prompt version: v3_original_demo_boundary_prompt
Class metadata loaded successfully.

0: Abusive/Offensive
1: Normal
2: Religious Hate
3: Sexism
4: Profane

In [14]:
# ============================================================
# BUILD FINAL FEW-SHOT GENERATION PROMPT
# ============================================================

def build_few_shot_messages(
    class_id,
    demonstrations,
):
    """
    Build the production few-shot prompt for one RUHSOLD class.
    """

    if class_id not in CLASS_METADATA:
        raise ValueError(
            f"Unknown class ID: {class_id}. "
            f"Valid IDs: {list(CLASS_METADATA.keys())}"
        )

    class_info = CLASS_METADATA[class_id]

    # --------------------------------------------------------
    # Clean demonstrations
    # --------------------------------------------------------

    demonstration_texts = [
        str(text).strip()
        for text in demonstrations
        if pd.notna(text)
        and str(text).strip()
    ]

    if len(demonstration_texts) != N_DEMONSTRATIONS:
        raise ValueError(
            f"Expected {N_DEMONSTRATIONS} demonstrations, "
            f"received {len(demonstration_texts)}."
        )

    if len(demonstration_texts) != len(
        set(demonstration_texts)
    ):
        raise ValueError(
            "Duplicate demonstrations were supplied "
            "to the prompt builder."
        )

    # --------------------------------------------------------
    # Format examples
    # --------------------------------------------------------

    formatted_examples = "\n".join(
        f"Example {index}: {text}"
        for index, text in enumerate(
            demonstration_texts,
            start=1,
        )
    )

    # --------------------------------------------------------
    # Class-specific generation requirement
    # --------------------------------------------------------

    if class_id == 2:

        class_specific_requirement = """
- The generated post MUST clearly express hostility toward a person
  or group because of their religion, religious belief, or religious identity.
- Simply using profanity or insulting somebody is NOT sufficient.
- Simply mentioning a religion or religious identity is NOT sufficient.
- The religious identity must be directly connected to the hostility.
""".strip()

    elif class_id == 3:

        class_specific_requirement = """
- The generated post MUST clearly express sexism, gender-based hostility,
  gender stereotyping, or degradation based on gender or sexual orientation.
- Generic profanity or a generic personal insult is NOT sufficient.
- Sexual or vulgar language alone is NOT sufficient.
- Gender or sexual identity must be directly connected to the hostility,
  stereotype, or degradation.
""".strip()

    elif class_id == 4:

        class_specific_requirement = """
- The generated post MUST contain profanity used as a general expression,
  exclamation, intensifier, frustration, or vulgar remark.
- The profanity must NOT primarily attack a specific person or group.
- Do NOT generate religious hate or gender-based hostility.
- Do NOT turn the post into a targeted personal insult.
""".strip()

    else:

        class_specific_requirement = """
- The meaning of the post must clearly match the target class.
""".strip()

    # --------------------------------------------------------
    # Final production prompt
    # --------------------------------------------------------

    instruction = f"""
You are generating synthetic Roman Urdu social-media posts for an
academic hate-speech classification dataset.

Target class: {class_info["label"]}

Definition:
{class_info["definition"]}

Important class boundary:
{class_info["boundary"]}

Real examples from the target class:

{formatted_examples}

Generate exactly one new, natural and informal Roman Urdu social-media
post that clearly belongs to the target class.

Requirements:
- Write primarily in Roman Urdu using the Latin alphabet.
- Natural English code-mixing is allowed.
{class_specific_requirement}
- Do not copy or closely paraphrase the examples.
- Do not include a label, explanation, translation, or quotation marks.
- Return only the generated post.
""".strip()

    return [
        {
            "role": "user",
            "content": instruction,
        }
    ]

In [15]:
# ============================================================
# TEST FINAL PROMPT
# ============================================================

test_demonstrations = sample_demonstrations(
    dataframe=demonstration_pool,
    class_id=3,
    n_examples=N_DEMONSTRATIONS,
    random_state=42,
)

test_messages = build_few_shot_messages(
    class_id=3,
    demonstrations=test_demonstrations,
)

print(test_messages[0]["content"])

You are generating synthetic Roman Urdu social-media posts for an
academic hate-speech classification dataset.

Target class: Sexism

Definition:
Language expressing hatred towards a targeted individual or group because of gender or sexual orientation.

Important class boundary:
Gender or sexual orientation must be the main reason for the hostility. General insults, sexual vulgarity, or references to female relatives without gender-based hatred are not Sexism.

Real examples from the target class:

Example 1: gashti orat tujhy koi amreci ni mila abi tak jo teri garmi ko thik kry kise gashti maa ki baiti,
Example 2: yar is pagal ko dafa karo islam ko badnam kr rahi ha randi kahin ki.ak video men nangi ho jati or agli video men hajan ban jati ha
Example 3: sir gazhi hijra hy ap bhe dp laga lein pta tu chly ap  kya cheez ho
Example 4: bc nasal ki randi

Generate exactly one new, natural and informal Roman Urdu social-media
post that clearly belongs to the target class.

Requirements:
- Write primarily in Roman Urdu using the Latin alphabet.
- Natural English code-mixing is allowed.
- The generated post MUST clearly express sexism, gender-based hostility,
  gender stereotyping, or degradation based on gender or sexual orientation.
- Generic profanity or a generic personal insult is NOT sufficient.
- Sexual or vulgar language alone is NOT sufficient.
- Gender or sexual identity must be directly connected to the hostility,
  stereotype, or degradation.
- Do not copy or closely paraphrase the examples.
- Do not include a label, explanation, translation, or quotation marks.
- Return only the generated post.

In [16]:

GENERATION_CONFIG = {
    "max_new_tokens": 60,
    "do_sample": True,
    "temperature": 0.7,
    "top_p": 0.90,
    "repetition_penalty": 1.15,
}

In [17]:
@torch.inference_mode()
def generate_one(
    model,
    messages,
    seed,
    generation_config=None,
):
    if generation_config is None:
        generation_config = GENERATION_CONFIG

    random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    model_inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
        add_generation_prompt=True,
    )

    model_inputs = {
        key: value.to(model.device)
        for key, value in model_inputs.items()
    }

    output_ids = model.generate(
        **model_inputs,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id,
        **generation_config,
    )

    prompt_length = (
        model_inputs["input_ids"]
        .shape[1]
    )

    generated_ids = output_ids[
        0,
        prompt_length:
    ]

    generated_text = tokenizer.decode(
        generated_ids,
        skip_special_tokens=True,
    ).strip()

    return generated_text

In [33]:
RELIGIOUS_PROTOTYPE_KEEP_IDS = [
    2, 3, 5, 7, 8, 10, 11, 13, 18, 23,
    33, 34, 37, 38, 41, 48, 50, 57, 60, 62,
    63, 65, 68, 71, 74, 75, 76, 78, 86, 92,
    94, 98, 99, 100, 107, 109, 118, 124, 125, 131,
    136, 138, 140, 150, 153, 155, 157, 160, 161, 162,
    163, 165, 180, 182, 189, 193, 198, 200, 209, 220,
    222, 224, 227, 229, 232, 237, 238, 243, 247, 254,
    255, 262, 268, 269, 270, 276, 279, 292, 296, 308,
    313, 315, 320, 327, 330, 336, 338, 340, 343, 345,
    347, 348, 350, 358, 359, 376, 384, 387, 389, 391,
    398, 401, 405, 412, 427, 430, 432, 435, 439, 440,
    449, 452, 454, 457, 468, 486, 494, 498
]

In [34]:
# ============================================================
# PREVIEW FINAL PRODUCTION GENERATIONS
# ============================================================

def preview_generations(
    class_id,
    n_samples=5,
    start_index=0,
    show_demonstrations=False,
):
    """
    Generate a small preview batch using the final
    production prompting strategy.
    """

    if class_id not in CLASS_METADATA:
        raise ValueError(
            f"Unknown class ID: {class_id}"
        )

    # --------------------------------------------------------
    # Select demonstration source
    # --------------------------------------------------------

    if class_id == 2:

        demo_source_df = religious_prototype_pool

        demo_source_name = (
            "Shortlisted authentic RUHSOLD Religious Hate examples"
        )

    elif class_id == 3:

        demo_source_df = sexism_prototype_pool

        demo_source_name = (
            "Shortlisted authentic RUHSOLD Sexism examples"
        )

    elif class_id == 4:

        demo_source_df = profane_prototype_pool

        demo_source_name = (
            "Shortlisted authentic RUHSOLD Profane examples"
        )

    else:

        demo_source_df = demonstration_pool

        demo_source_name = (
            "Random authentic same-class RUHSOLD examples"
        )

    # --------------------------------------------------------
    # Display generation setup
    # --------------------------------------------------------

    print("=" * 80)

    print(
        "Target class:",
        CLASS_METADATA[class_id]["label"]
    )

    print(
        "Demonstration source:",
        demo_source_name
    )

    print(
        "Demonstration pool size:",
        len(demo_source_df)
    )

    print("=" * 80)

    results = []

    # --------------------------------------------------------
    # Generate preview samples
    # --------------------------------------------------------

    for offset in range(n_samples):

        sample_index = (
            start_index + offset
        )

        # ----------------------------------------------------
        # Reproducible seeds
        # ----------------------------------------------------

        generation_seed = (
            BASE_GENERATION_SEED
            + class_id * 100000
            + sample_index
        )

        demonstration_seed = (
            BASE_DEMONSTRATION_SEED
            + class_id * 100000
            + sample_index
        )

        # ----------------------------------------------------
        # Sample four unique authentic demonstrations
        # ----------------------------------------------------

        demonstrations = sample_demonstrations(
            dataframe=demo_source_df,
            class_id=class_id,
            n_examples=N_DEMONSTRATIONS,
            random_state=demonstration_seed,
        )

        # ----------------------------------------------------
        # Build prompt
        # ----------------------------------------------------

        messages = build_few_shot_messages(
            class_id=class_id,
            demonstrations=demonstrations,
        )

        # ----------------------------------------------------
        # Generate
        # ----------------------------------------------------

        generated_text = generate_one(
            model=finetuned_model,
            messages=messages,
            seed=generation_seed,
        )

        # ----------------------------------------------------
        # Display
        # ----------------------------------------------------

        print(
            f"\nSample {offset + 1}"
        )

        print("-" * 60)

        print(
            "Sample index:",
            sample_index
        )

        print(
            "Generation seed:",
            generation_seed
        )

        print(
            "Demonstration seed:",
            demonstration_seed
        )

        if show_demonstrations:

            print("\nDemonstrations:")

            for index, example in enumerate(
                demonstrations,
                start=1,
            ):
                print(
                    f"{index}. {example}"
                )

        print("\nGenerated output:")
        print(generated_text)

        # ----------------------------------------------------
        # Record result
        # ----------------------------------------------------

        results.append({
            "sample_index":
                sample_index,

            "class_id":
                class_id,

            "target_label":
                CLASS_METADATA[
                    class_id
                ]["label"],

            "generation_seed":
                generation_seed,

            "demonstration_seed":
                demonstration_seed,

            "prompt_version":
                PROMPT_VERSION,

            "prompting_strategy":
                "4-shot random authentic same-class",

            "demonstration_source":
                demo_source_name,

            "demonstration_pool_size":
                len(demo_source_df),

            "demonstrations":
                demonstrations,

            "generated_text":
                generated_text,
        })

    return results

In [40]:
# ============================================================
# CHECK AVAILABLE RELIGIOUS-HATE DATAFRAMES
# ============================================================

for name, obj in globals().items():

    if (
        isinstance(obj, pd.DataFrame)
        and "relig" in name.lower()
    ):
        print(
            name,
            obj.shape,
            obj.columns.tolist()
        )

In [41]:
# ============================================================
# CHECK ALL DATAFRAMES CURRENTLY IN MEMORY
# ============================================================

for name, obj in list(globals().items()):

    if isinstance(obj, pd.DataFrame):

        print(
            f"{name}: "
            f"shape={obj.shape}"
        )

        print(
            "Columns:",
            obj.columns.tolist()
        )

        print("-" * 80)

_: shape=(5, 2)
Columns: ['text', 'label']
--------------------------------------------------------------------------------
train_df: shape=(6401, 2)
Columns: ['text', 'label']
--------------------------------------------------------------------------------
_4: shape=(5, 2)
Columns: ['text', 'label']
--------------------------------------------------------------------------------
demonstration_pool: shape=(6401, 2)
Columns: ['text', 'label']
--------------------------------------------------------------------------------
sexism_examples: shape=(10, 2)
Columns: ['text', 'label']
--------------------------------------------------------------------------------
sexism_candidates: shape=(535, 3)
Columns: ['review_id', 'text', 'label']
--------------------------------------------------------------------------------
sexism_prototype_pool: shape=(40, 2)
Columns: ['text', 'label']
--------------------------------------------------------------------------------
profane_candidates: shape=(410, 2)
Columns: ['text', 'label']
--------------------------------------------------------------------------------
profane_prototype_pool: shape=(40, 2)
Columns: ['text', 'label']
--------------------------------------------------------------------------------

In [42]:
# ============================================================
# RECONSTRUCT RELIGIOUS HATE PROTOTYPE POOL
# ============================================================

# First isolate authentic Religious Hate examples
religious_candidates = (
    demonstration_pool[
        demonstration_pool["label"] == 2
    ]
    .copy()
    .reset_index(drop=True)
)

print(
    "Religious Hate authentic candidates:",
    len(religious_candidates)
)

# ------------------------------------------------------------
# Rebuild curated prototype pool from saved keep IDs
# ------------------------------------------------------------

religious_prototype_pool = (
    religious_candidates
    .iloc[
        RELIGIOUS_PROTOTYPE_KEEP_IDS
    ]
    [
        [
            "text",
            "label",
        ]
    ]
    .copy()
    .reset_index(drop=True)
)

print(
    "Religious prototype pool size:",
    len(religious_prototype_pool)
)

print(
    "\nClass distribution:"
)

print(
    religious_prototype_pool[
        "label"
    ].value_counts()
)

display(
    religious_prototype_pool.head(10)
)

Religious Hate authentic candidates: 500
Religious prototype pool size: 118

Class distribution:
label
2    118
Name: count, dtype: int64

,text,label
0,"insaniyat ko bache rahne do, jis mazhab me janwar ka gala ret ke khushi banti hai, jis mazhab me soorma logo ko 72 virgin ladkiya baati jaati, jo duniya pe kabze ke sapne dekhta ho us mazhab se duuri banane me hi insaniyat ki bhalayi hai.",2
1,1 balatkari muslim 3 balatkari tera baap hindu h uske bare m kuch bol be,2
2,hindu dharm ka matlab samajh pehle puppet khali bhaunk aur bhaunk iam enjoying ur bark 😂😂😂😂,2
3,jahil k bachy kahan likha h k gair mazhb sy nikaah jaiz ha... tmari gand me jo keera ha wo nhi merna... khoty khany waly... yahoodi kahan sy hogaey ahle kitaab ....tm.b yahoodi to nhi,2
4,lanat abbtknews k khilaf trend bnane walye yazeedion pe r bibi k dushmano p bhi,2
5,teri maa ka halala kra rha tha koi problem madarjat bhosdike mulle,2
6,apne profile mein whats app me fb twitter mein is bahadur nojawaan ki pic lga kr islam se or nabi ke din se mhbt ka izhaar kren or itna share kren ek yahoodi apne na pak iradoon se baaz ajaye is shakhs ne quraan pak ki hifazahat mein ek bhtareen mhbt ka jita jagta sabot dia hai,2
7,yahoodi ko hitler ne chora or general ne in jaajoon ko chor k dhkya k ye kai hain.😂,2
8,lul bukhari ye tum nahe tumaray yahoodi or hindu thuku bol rahay hain jin ko army sey bahot hi zeda takleef hai...🖕,2
9,pislam me media ka estemal kerna haram hai halala ki paidais,2

In [43]:
# ============================================================
# SANITY CHECK ALL CURATED DEMONSTRATION POOLS
# ============================================================

print(
    "Religious Hate:",
    len(religious_prototype_pool),
    "samples"
)

print(
    "Sexism:",
    len(sexism_prototype_pool),
    "samples"
)

print(
    "Profane:",
    len(profane_prototype_pool),
    "samples"
)

assert set(
    religious_prototype_pool["label"].unique()
) == {2}

assert set(
    sexism_prototype_pool["label"].unique()
) == {3}

assert set(
    profane_prototype_pool["label"].unique()
) == {4}

print(
    "\nAll curated pools are valid."
)

Religious Hate: 118 samples
Sexism: 40 samples
Profane: 40 samples

All curated pools are valid.

In [44]:
# ============================================================
# SAVE CURATED DEMONSTRATION POOLS
# ============================================================

CURATED_POOL_DIR = (
    GENERATION_DIR
    / "curated_demonstration_pools"
)

CURATED_POOL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

religious_prototype_pool.to_csv(
    CURATED_POOL_DIR
    / "religious_hate_prototype_pool.csv",
    index=False,
    encoding="utf-8"
)

sexism_prototype_pool.to_csv(
    CURATED_POOL_DIR
    / "sexism_prototype_pool.csv",
    index=False,
    encoding="utf-8"
)

profane_prototype_pool.to_csv(
    CURATED_POOL_DIR
    / "profane_prototype_pool.csv",
    index=False,
    encoding="utf-8"
)

print(
    "Curated demonstration pools saved."
)

Curated demonstration pools saved.

In [45]:
# ============================================================
# FINAL SANITY CHECK
# Religious Hate: 5 samples
# ============================================================

religious_test_samples = preview_generations(
    class_id=2,
    n_samples=5,
    start_index=100,
    show_demonstrations=True,
)

================================================================================
Target class: Religious Hate
Demonstration source: Shortlisted authentic RUHSOLD Religious Hate examples
Demonstration pool size: 118
================================================================================

Sample 1
------------------------------------------------------------
Sample index: 100
Generation seed: 201100
Demonstration seed: 205100

Demonstrations:
1. kaafir tujhe kuch nai malum
2. madarchod muslaman ki kaum madarchod saalo ka imaan nahi hai bheno ko chod te hai bhen ke lode harmazaade uskiye apni  maa ki chut bhi chodta hoga aur chuswata hoga logo se saare musalamaan raand ki olad islam ki maa ki chut
3. tum log yahoodi ho kisi ko shuck nahi hona chaheye bus kafi hogae musalmanon ko aur dhoka na dou👹
4. #stopisraeliterror   yahoodi mulk jisey israel ka naam diya gaya najaiz hai yahoodi sabse bada dahshatgard

Generated output:
abe kuttay ye mullah jo teri behn ko chod raha hai wo maulana hein

Sample 2
------------------------------------------------------------
Sample index: 101
Generation seed: 201101
Demonstration seed: 205101

Demonstrations:
1. imran qadyani yahoodi agent hy pti ki 18 bank account hy jis may qadyani yahoodi hondo ny funding ki hy . gold smith jimaima aneel musrst . atif miaan sub qadyani yahoodi hy
2. please don't share his obnoxious face to me. below is the image of the book rohani khzain from ahmedi's official website see what your evil messiah has declared god but you had said you have read the books of mirza and accepted him mehdi may god give you hidyath
3. madarchod muslaman ki kaum madarchod saalo ka imaan nahi hai bheno ko chod te hai bhen ke lode harmazaade uskiye apni  maa ki chut bhi chodta hoga aur chuswata hoga logo se saare musalamaan raand ki olad islam ki maa ki chut
4. teri maa ka halala kra rha tha koi problem madarjat bhosdike mulle

Generated output:
i am really happy for you as well my friend, allah will always be with us inshaallah

Sample 3
------------------------------------------------------------
Sample index: 102
Generation seed: 201102
Demonstration seed: 205102

Demonstrations:
1. please all muslims come one page and unite  insha allah   yahoodi isreal finished all
2. another endian hijra coward hindu terrorist army soldier dispatched to shamshangarh by pakistan army i want more endian hindu terrorist dead so keep it up pakistan
3. madarchod muslaman ki kaum madarchod saalo ka imaan nahi hai bheno ko chod te hai bhen ke lode harmazaade uskiye apni  maa ki chut bhi chodta hoga aur chuswata hoga logo se saare musalamaan raand ki olad islam ki maa ki chut
4. phir in yahodi khanzeer logo ko pata chalaiga kai kia ta aur kia nahen ye sirf dajjal kai liye aisa kar rahai hain kyunkai ye yahodi log khazeer log dajjal ko apna leader samjhtai hain aur tumhara pura bollywood bollyminati ban chuka hain tumharai dimagh ko programming ki ja rah

Generated output:
nikl jaa bhosadi

Sample 4
------------------------------------------------------------
Sample index: 103
Generation seed: 201103
Demonstration seed: 205103

Demonstrations:
1. kitane maulviyon ne tumhari ammi jaan ka halala kiya hoga tab jakar tum jaisa suar nikla hoga .. ye bhi to bta re mulle..
2. afghanio ne tme hindu se bachaya,randi k aulaad tareekh paro tm wo ganda khoon ho,jo siko aour hindu ki rape se paida woe ho,tme kalima tho sikaya afghano ne,magar tmari gandi dna wai ranjeet sing wali a,randi k aulaad tm ne kah pana di,am pashtono ne di,apnay bio ko hera mandi
3. please don't share his obnoxious face to me. below is the image of the book rohani khzain from ahmedi's official website see what your evil messiah has declared god but you had said you have read the books of mirza and accepted him mehdi may god give you hidyath
4. another endian hijra coward hindu terrorist army soldier dispatched to shamshangarh by pakistan army i want more endian hindu terrorist dead so keep it up pakistan

Generated output:
kuch bol do charsi randi k aulad

Sample 5
------------------------------------------------------------
Sample index: 104
Generation seed: 201104
Demonstration seed: 205104

Demonstrations:
1. ho gaye hy aur han aj jo ye sekhon k liye kar raha hy ye whoi sekh hy jub pakistan azad howa tha aur muslmano ne jub india sa hijrat ki tub sub zada qatal muslim ko in sekhon ne kiya tha par afsos ap jesy log is yahodi e agent ko ek islami leader mante ho phir kasm khao k allah
2. no no ...... hindu na kah mujhe ........islam bura maan jayega .......kaafir kah kaafir...
3. bilkul,itny lecture milny hain jese christmas or new year pe milty hain ,kya apko pata bhi hai k kaafir janwaro k haqq main dua bhi nahi krni chahye
4. surprise!  surprise!  majority of the muslims are at just in different levels of "usman khan" ranging from mild to extreme (except ahmadiya may be, but they are not "real muslims")  that's from a person living in a country with 95% muslim    https://t.co/hq35u2xrrk,2009-05-25 17:25:26,sydney, new south wales

Generated output:
😂😂😂😂 ye nai aby gandu

In [ ]:
# ============================================================
# PREVIEW WITH BASE MISTRAL
# ADAPTER DISABLED
# ============================================================

def preview_base_model_generations(
    class_id,
    n_samples=5,
    start_index=0,
    show_demonstrations=False,
):
    """
    Generate using the same prompts and seeds,
    but with the QLoRA adapter temporarily disabled.
    """

    if class_id not in CLASS_METADATA:
        raise ValueError(
            f"Unknown class ID: {class_id}"
        )

    # --------------------------------------------------------
    # Select demonstration source
    # --------------------------------------------------------

    if class_id == 2:
        demo_source_df = religious_prototype_pool
        demo_source_name = (
            "Shortlisted authentic RUHSOLD Religious Hate examples"
        )
    else:
        demo_source_df = demonstration_pool
        demo_source_name = (
            "Random authentic same-class RUHSOLD examples"
        )

    print("=" * 80)
    print(
        "MODEL: BASE MISTRAL (QLoRA ADAPTER DISABLED)"
    )
    print(
        "Target class:",
        CLASS_METADATA[class_id]["label"]
    )
    print(
        "Demonstration source:",
        demo_source_name
    )
    print("=" * 80)

    results = []

    # --------------------------------------------------------
    # Temporarily disable QLoRA adapter
    # --------------------------------------------------------

    with finetuned_model.disable_adapter():

        for offset in range(n_samples):

            sample_index = start_index + offset

            # ------------------------------------------------
            # Reproducible seeds
            # ------------------------------------------------

            generation_seed = (
                BASE_GENERATION_SEED
                + class_id * 100000
                + sample_index
            )

            demonstration_seed = (
                BASE_DEMONSTRATION_SEED
                + class_id * 100000
                + sample_index
            )

            # ------------------------------------------------
            # Sample demonstrations
            # ------------------------------------------------

            demonstrations = sample_demonstrations(
                dataframe=demo_source_df,
                class_id=class_id,
                n_examples=N_DEMONSTRATIONS,
                random_state=demonstration_seed,
            )

            # ------------------------------------------------
            # Build identical prompt
            # ------------------------------------------------

            messages = build_few_shot_messages(
                class_id=class_id,
                demonstrations=demonstrations,
            )

            # ------------------------------------------------
            # Generate
            # ------------------------------------------------

            generated_text = generate_one(
                model=finetuned_model,
                messages=messages,
                seed=generation_seed,
            )

            # ------------------------------------------------
            # Display
            # ------------------------------------------------

            print(
                f"\nSample {offset + 1}"
            )

            print("-" * 60)

            print(
                "Sample index:",
                sample_index
            )

            print(
                "Generation seed:",
                generation_seed
            )

            print(
                "Demonstration seed:",
                demonstration_seed
            )

            if show_demonstrations:

                print("\nDemonstrations:")

                for index, example in enumerate(
                    demonstrations,
                    start=1,
                ):
                    print(
                        f"{index}. {example}"
                    )

            print("\nGenerated output:")
            print(generated_text)

            # ------------------------------------------------
            # Save result
            # ------------------------------------------------

            results.append({
                "sample_index":
                    sample_index,

                "class_id":
                    class_id,

                "target_label":
                    CLASS_METADATA[
                        class_id
                    ]["label"],

                "generation_seed":
                    generation_seed,

                "demonstration_seed":
                    demonstration_seed,

                "model":
                    "Base Mistral-7B-Instruct-v0.2",

                "adapter":
                    "disabled",

                "demonstrations":
                    demonstrations,

                "generated_text":
                    generated_text,
            })

    return results

In [ ]:
religious_base_test_samples = preview_base_model_generations(
    class_id=2,
    n_samples=5,
    start_index=100,
    show_demonstrations=True,
)

In [ ]:
# ============================================================
# GENERATE PILOT DATASET
# ============================================================

def generate_pilot_dataset(
    class_id,
    n_samples=100,
    start_index=0,
    save_every=10,
):
    """
    Generate and save a reproducible pilot synthetic dataset
    for one RUHSOLD target class.

    Religious Hate uses the curated Religious Hate prototype pool.
    Sexism uses the curated Sexism prototype pool.
    Profane uses the curated Profane prototype pool.
    Other classes use the general authentic demonstration pool.
    """

    if class_id not in CLASS_METADATA:
        raise ValueError(
            f"Unknown class ID: {class_id}. "
            f"Valid IDs: {list(CLASS_METADATA.keys())}"
        )

    # --------------------------------------------------------
    # Select demonstration source
    # --------------------------------------------------------

    if class_id == 2:

        demo_source_df = religious_prototype_pool

        demo_source_name = (
            "Shortlisted authentic RUHSOLD Religious Hate examples"
        )

    elif class_id == 3:

        demo_source_df = sexism_prototype_pool

        demo_source_name = (
            "Shortlisted authentic RUHSOLD Sexism examples"
        )

    elif class_id == 4:

        demo_source_df = profane_prototype_pool

        demo_source_name = (
            "Shortlisted authentic RUHSOLD Profane examples"
        )

    else:

        demo_source_df = demonstration_pool

        demo_source_name = (
            "Random authentic same-class RUHSOLD examples"
        )

    # --------------------------------------------------------
    # Output directory
    # --------------------------------------------------------

    PILOT_OUTPUT_DIR = (
        PROJECT_ROOT
        / "fine tuning"
        / "outputs"
        / "synthetic_generation"
        / "pilot"
    )

    PILOT_OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    # --------------------------------------------------------
    # Build output filename
    # --------------------------------------------------------

    class_name_for_file = (
        CLASS_METADATA[class_id]["label"]
        .lower()
        .replace("/", "_")
        .replace(" ", "_")
    )

    output_path = (
        PILOT_OUTPUT_DIR
        / f"{class_name_for_file}_raw_pilot_{n_samples}.csv"
    )

    # --------------------------------------------------------
    # Display setup
    # --------------------------------------------------------

    print("=" * 80)
    print("Generating pilot dataset")

    print(
        "Class:",
        CLASS_METADATA[class_id]["label"]
    )

    print(
        "Demonstration source:",
        demo_source_name
    )

    print(
        "Demonstration pool size:",
        len(demo_source_df)
    )

    print(
        "Samples:",
        n_samples
    )

    print(
        "Output:",
        output_path
    )

    print("=" * 80)

    # --------------------------------------------------------
    # Generate samples
    # --------------------------------------------------------

    results = []

    for offset in range(n_samples):

        sample_index = (
            start_index + offset
        )

        # ----------------------------------------------------
        # Reproducible seeds
        # ----------------------------------------------------

        generation_seed = (
            BASE_GENERATION_SEED
            + class_id * 100000
            + sample_index
        )

        demonstration_seed = (
            BASE_DEMONSTRATION_SEED
            + class_id * 100000
            + sample_index
        )

        # ----------------------------------------------------
        # Sample demonstrations
        # ----------------------------------------------------

        demonstrations = sample_demonstrations(
            dataframe=demo_source_df,
            class_id=class_id,
            n_examples=N_DEMONSTRATIONS,
            random_state=demonstration_seed,
        )

        # ----------------------------------------------------
        # Build generation prompt
        # ----------------------------------------------------

        messages = build_few_shot_messages(
            class_id=class_id,
            demonstrations=demonstrations,
        )

        # ----------------------------------------------------
        # Generate synthetic sample
        # ----------------------------------------------------

        generated_text = generate_one(
            model=finetuned_model,
            messages=messages,
            seed=generation_seed,
        )

        # ----------------------------------------------------
        # Store generation record
        # ----------------------------------------------------

        result = {
            "sample_index":
                sample_index,

            "class_id":
                class_id,

            "target_label":
                CLASS_METADATA[
                    class_id
                ]["label"],

            "generation_seed":
                generation_seed,

            "demonstration_seed":
                demonstration_seed,

            "prompt_version":
                PROMPT_VERSION,

            "prompting_strategy":
                "4-shot random authentic same-class",

            "demonstration_source":
                demo_source_name,

            "demonstration_pool_size":
                len(demo_source_df),

            "demo_1":
                demonstrations[0],

            "demo_2":
                demonstrations[1],

            "demo_3":
                demonstrations[2],

            "demo_4":
                demonstrations[3],

            "generated_text":
                generated_text,
        }

        results.append(result)

        # ----------------------------------------------------
        # Periodic checkpoint save
        # ----------------------------------------------------

        if (
            (offset + 1) % save_every == 0
            or
            (offset + 1) == n_samples
        ):

            temporary_df = pd.DataFrame(
                results
            )

            temporary_df.to_csv(
                output_path,
                index=False,
                encoding="utf-8"
            )

            print(
                f"Saved {offset + 1}/{n_samples}"
            )

    # --------------------------------------------------------
    # Final dataframe
    # --------------------------------------------------------

    pilot_df = pd.DataFrame(
        results
    )

    # --------------------------------------------------------
    # Final save
    # --------------------------------------------------------

    pilot_df.to_csv(
        output_path,
        index=False,
        encoding="utf-8"
    )

    print("\nGeneration complete.")

    print(
        "Shape:",
        pilot_df.shape
    )

    print(
        "Saved to:",
        output_path
    )

    return pilot_df

In [54]:
religious_pilot_df = generate_pilot_dataset(
    class_id=2,
    n_samples=100,
    start_index=0,
    save_every=10,
)

================================================================================
Generating pilot dataset
Class: Religious Hate
Samples: 100
Output: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/pilot/religious_hate_raw_pilot_100.csv
================================================================================
Saved 10/100
Saved 20/100
Saved 30/100
Saved 40/100
Saved 50/100
Saved 60/100
Saved 70/100
Saved 80/100
Saved 90/100
Saved 100/100

Generation complete.
Shape: (100, 14)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/pilot/religious_hate_raw_pilot_100.csv

In [55]:
religious_pilot_df[
    [
        "sample_index",
        "generated_text",
    ]
].head(20)

,sample_index,generated_text
0,0,tery baap ne tu gaddar hi banaya tha...tum sab muslim hn or bhag jao
1,1,teri maa ki phudi mein lanti tere jaise muslamanon ke nikal
2,2,yar baat mat karte tu apny baap ka baap sy larkiyon ko bachana chahtay ho???
3,3,mulle bharwe yahan wahan aati hai ye duniya hamara hi mulk hai
4,4,"abey, behan tu samaj kro, mera jaan hai"
5,5,apni maa ko goli marne wala teri maa chod gayee thi saalee
6,6,ye logon ne baz e mohtaj ki zarurat hi nahi kaha thi usko phly tumhee yahan se pta chala ga
7,7,tere baap ke pass pakistan ki dushman hain yahodi
8,8,aurat march se harami halala ki pedawar
9,9,jb tu hmari soch sy mohsin na ho ga tab to esa hi karwa dunga koi
10,10,kuch bhi matlab tu kisi ka charsi hi nikla hay
11,11,wo kya bolta hai? 😂
12,12,tu lund peetha hai nikal dunga
13,13,tum logon ki maa ko goli maar do
14,14,woh bacha mulla hai jo hamari madina ki goliyan ka sath dikh raha hai
15,15,#mahirakapashteen is a london based anti-ahmadiya and qadyani agent who is spreading lies about imran khan on social media
16,16,apne gand mein kuch nhi dekhte yahan se nahi bolta
17,17,bajwa ki bat kr rha thi ye gandhi ka shoq bnaya
18,18,lanati yahodi kuttay
19,19,kya dekh lo ye bhai hain?

In [22]:
# ============================================================
# FINAL SANITY CHECK
# Sexism: 5 samples
# ============================================================

sexism_test_samples = preview_generations(
    class_id=3,
    n_samples=5,
    start_index=200,
    show_demonstrations=True,
)

================================================================================
Target class: Sexism
Demonstration source: Random authentic same-class RUHSOLD examples
================================================================================

Sample 1
------------------------------------------------------------
Sample index: 200
Generation seed: 301200
Demonstration seed: 305200

Demonstrations:
1. aur yeah hijra #billorani kuch nahin ban sakta. 🤮 baray moun wali looti. 🙄 #bilawajabhutto #accidentalchairman #fakebhutto #abubachao
2. bata ab aurat ke naam ke kalakh
3. this randi should also tell thst the babri masjid was built on demolished temple
4. chhee kitni gandi shakal 🤮🤮🤮🤣🤣😂 bhakkk randi saali jisko manti hai usse to dar

Generated output:
nhi to acha hoga..😂

Sample 2
------------------------------------------------------------
Sample index: 201
Generation seed: 301201
Demonstration seed: 305201

Demonstrations:
1. #rashamidesai tu randi moti apni maa ko bech chuki hai ...kisi aur ke hatho..to apni awkat ne rah kar game plan kar ...arhan to vaduaa hai...ram mandir ban rha hai na..but tu chud rahi hai kisi aur ka bister garam kar rhi hai
2. aaja tjhe phir se maza dun
3. randi in mandi kutya tu bhi reham bn rhi h madarchod gshti minten kr k pic bnwati ho aor phir bkwas krti ho u bastrd
4. ise khud hi pata nahin hai hijra hai ya ladka hai ya ladki hai sala suar ka baccha main bhi muslim religion ko lekar koi baat karun to yah gussa ho jaega

Generated output:
teri jaldi aakar aaj tak bhenchod nikla huwa hai

Sample 3
------------------------------------------------------------
Sample index: 202
Generation seed: 301202
Demonstration seed: 305202

Demonstrations:
1. bc kali kutiya..
2. aaja tjhe phir se maza dun
3. tu bhi kyu nahi jal gayi saath mein randi ?
4. especially randi ki aami ko thok denge

Generated output:
tera maa chod dunga kutte

Sample 4
------------------------------------------------------------
Sample index: 203
Generation seed: 301203
Demonstration seed: 305203

Demonstrations:
1. rundi fuckoff
2. tu ek number ka hijra hai aftab tera baap terrorist hai aur tu security guard ka naukari karta hai isiliye do rupaye ke liye twitter per aaya hai yah sach accept karle kyon jhooth bolata hai ki tere pass indian visa hai so kar jahid jihadi tourist
3. teri chut me sabhi bhaiyo ka lund reply de randi
4. she is bussy in dreaming of akhrot 😭😭😭,2016-09-24 17:53:58

Generated output:
i am sorry for this but you have fucked up big time by your stupid comment on the woman of our country who has been brutally murdered by a hindu goonda 🙏😥

Sample 5
------------------------------------------------------------
Sample index: 204
Generation seed: 301204
Demonstration seed: 305204

Demonstrations:
1. apnay tou pura chara tha "ahmaq" ko!!!!
2. oe kanjar oraat bar bar bhagnay ki bat na kar mujhy pata hai tu jana chahta hai randi k bachy magar mai aj tera zor dikhta hai kinti gand mmai tao hai tera jispe tu dazzy maf ra hai bhanay tu na bana or shabash mujhsy chudwata reh apni maa
3. ya rundi k buchy set ho jaen gy dont worry . kuch din sabr
4. ye muh parde ke liye nhi chupaya  ye hijra hai es liye muh chupaya hai😜

Generated output:
bhenchod kutty bharwe

In [21]:
# ============================================================
# Display ALL original RUHSOLD Sexism samples for review
# ============================================================

sexism_candidates = (
    demonstration_pool[
        demonstration_pool["label"] == 3
    ][["text", "label"]]
    .dropna(subset=["text"])
    .drop_duplicates(subset=["text"])
    .reset_index(drop=True)
)

# Add stable IDs for manual review and later selection
sexism_candidates.insert(
    0,
    "review_id",
    range(len(sexism_candidates))
)

# Display everything without truncating the text
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

print(
    "Total unique Sexism candidates:",
    len(sexism_candidates)
)

#display(sexism_candidates)

Total unique Sexism candidates: 535

In [22]:
# ============================================================
# SEXISM PROTOTYPE KEEP IDS
# ============================================================

SEXISM_PROTOTYPE_KEEP_IDS = [
    # Gender-role / women stereotypes
    18,
    67,
    70,
    92,
    95,
    124,
    153,
    161,
    179,
    190,
    222,
    241,
    269,
    271,
    290,
    310,
    324,
    359,
    432,
    459,
    466,
    470,
    476,
    514,

    # Gender identity / masculinity degradation
    14,
    78,
    123,
    217,
    221,
    331,
    337,
    367,
    414,
    417,
    478,
    509,

    # Explicit sexual / gendered degradation
    49,
    150,
    258,
    462,
]

In [23]:
# ============================================================
# CREATE SEXISM PROTOTYPE POOL
# ============================================================

sexism_prototype_pool = (
    sexism_candidates[
        sexism_candidates["review_id"].isin(
            SEXISM_PROTOTYPE_KEEP_IDS
        )
    ][
        [
            "text",
            "label",
        ]
    ]
    .drop_duplicates(
        subset=["text"]
    )
    .reset_index(drop=True)
)

print(
    "Sexism prototype candidates:",
    len(sexism_prototype_pool)
)

display(
    sexism_prototype_pool
)

Sexism prototype candidates: 40

,text,label
0,70 saal ka mard is better than a 30 year old hijra😅,3
1,jin ko hizab se nafrat he wo nangi ho k ghoome koi in pe thooke ga bhi nahi aurat khoobsurat pure libas me lagti he mawazna karlen,3
2,aisi or kis kis ki lund par uchel uchel kar moja lati ghar me.,3
3,#stopauratbarbadimarch aurat ghr k andr hi achi lgti he yu sarkon par nikalna kisi bhi aurat ki izzat par daag lga skta he,3
4,randi kise kahte ha aap hi bata do? ye word ghatiya women ke liye hi use karta ha ab deepika ghatiya ha to randi hi bolenge na,3
5,phir larky beard ky bagiar khusray q lgty hain wo bhi beard ky bagiar khubsurat lgny chahiye ?,3
6,original attitude boys ma hota ha aur fake girls ma,3
7,mard muhbt kr bhi ly tu aksar aurat he dhoka dy jati h usy 💔,3
8,ap ko mard banny ki acting pasand i? agr ni to hijra hi bany rahye sir ye mardo k kam hn hijro k ni.,3
9,acha tareka dhondha hai larkun ko ganda sabit karny ka but aesi neech harkat larkyan he kar sakti hain larky nahi.,3
10,aaaahhhhhh bhenchod.....jese tere is mangalsutra ki sahi jagah tere gale me nai balki mere mote kaale lund pr he.... vese hi tujh jesi chudakkad kuttiya ki jagah kewal mere pairo k niche he saali.... chal inbox me aa.....,3
11,jahiliyat ki v had hai ye apne ghar me slave ki tarh rahti hai aur bahar kutto jaise bhaunk rhi hai... shame on these ladies,3
12,"madum ap gharailo maon behno ki terha na blkeh on maon behno ki terha bhi nahi jo moaashrat main ghar sy bahir nikal ker apni , maan baap ki .belky pory moaashry ki izzat ka kgayal rekhti hain .ap oss catogary main ati hain .jisy rundi,jisy tawaif,fahasha, jisy badqar kehty hain",3
13,tum jesi ghatia aurat ka kam hi ni hai media par.kisi kothhay pe ja aur ulta late ja ke.begherat,3
14,aur jesi ghatia aurat ke mun se ye bat achi ni lagti. logon ko garam karnay wali machine.,3
15,muslim countries ki leaderships na mard napunsak or hijra hain.. in mein koi dum nahi.. ye kuch nahi kr sakty.. jinnah ki rooh tarapti hogi.. jinnah ne kashmir par attack ka order diya tha..,3
16,bc ghar wale bhi soch rahe honge yeh kya system paida ho gya sala lagta programing galat ho gayi.... sabsi badi confusion iske liye ladka dhundheyge yaa ladki😉,3
17,#stopauratbarbadimarch who are you for arguing our tradition and islamic manners you bluddy 2 takay ki aurat .,3
18,ek randi larki ko itni pazeerai di hai. smjh se bahir hai,3
19,teri chut me sabhi bhaiyo ka lund reply de randi,3
20,"ab iska sara credit har anchor le rha h jb k rape, ki asal jad h hi media jo mera jism.meri marzi, hareem.shah , qandeel bloch , valentine day pe program krty hn phr rape hi hn gy",3
21,agar aaj se 40 saal pehley isi tarha ke banner pakarh kar mera jism meri marzi waala naara aapki amma ne maara hota to aap is duniya main ye tweet karney ke liye maujood hi na hoteen 😑😑😑,3
22,we are supporting #islam and thank you #khalilurrahmanqamar for your beautiful comments against #gashti . agar ye #aurat hoti to na me aesi zuban use krta aur na koi gairatmand #admi use krta.,3
23,#auratmarch2020 mera jism allah ki marzi.. allah ka to hukam ha tum char dewari me raho .. nd ya nikl k apni nimaish karna chahten,3
24,you are just girlfriend material no one wants wife like you. itna jism jo sirf admi apni bivi ka dekhta h apka to sary jahan ne dekha h,3
25,bilo rani tumhari pehchan sirf or sirf hijra huna hai.. na mard,3
26,tu kyun ro rahe hai hijra? tera buddhe hijra to kamjor mard hai. uska kara nehi hota. 🤣🤣🤣🤣,3
27,"aurat ko islam nai galat lagta, ap log lagtay ho jo ye boltay hain k agar aurat ka rape hua to wo uski galtie usne sar par dupatta nai kiya us banday ki nahi wo bechara kesay control karay",3
28,"apko kehna chahye tha na mard hoon, na aurat hoo. main hijra hoon main hijra hoon, main parchi hoon, main defected hoon, main accidental chairman hoon. #joker420",3
29,teri bhosdi or boobs me parda mat kar...logo ko dekne de.dhake hoge to kaise pata chalega ki tu hijra nehi hai. hijra kahi ki.,3
30,roads pe lab coat b ap ki gender hi pehnti ha 😂,3
31,lalchi aurat paisa dekhti hai aur khandani aurat sirf sehrat dekhti hai,3
32,shazaib apni baji ko b bejna han aurat march ma agr itne he zruri hai to,3
33,tere jaise randiyo ki chudai ke liye to ham mard hain yaha pe,3
34,r mazy k bat mra jism wo auratn krti hn jin pr thokta bh koi nae.,3
35,apni behn ko bhejo gay na aurat march me??,3
36,dhoka khane k baad oska aitbar uth jata haa sbsee or dosre mard mai b interest ni rehta...ku k aurat jism k ley ni chahti jbk mard jism k ley chahta😌🙂,3
37,transgander madarchood hijra tu aik bara khoota ha haram zada,3
38,your leader is hijra that's why he is not living with his wife.,3
39,"yeh wesy koi bht e zyda ounchi nasal ki randi niqli h wesy , mtlb i can't even imagine koi bughaz or paisy k pechay itna b girr skta h, nehayat e nichly darjay ki baighairat aurat ho, aurat zaat ko b badnaam kea h isny apny wajood sy !! akhh thooo iski zaat pay",3

In [99]:
sexism_test_samples = preview_generations(
    class_id=3,
    n_samples=5,
    start_index=200,
    show_demonstrations=True,
)

================================================================================
Target class: Sexism
Demonstration source: Shortlisted authentic RUHSOLD Sexism examples
Demonstration pool size: 40
================================================================================

Sample 1
------------------------------------------------------------
Sample index: 200
Generation seed: 301200
Demonstration seed: 305200

Demonstrations:
1. original attitude boys ma hota ha aur fake girls ma
2. your leader  is hijra that's why he is not living with his wife.
3. yeh wesy koi bht e zyda ounchi nasal ki randi niqli h wesy , mtlb i can't even imagine koi bughaz or paisy k pechay itna b girr skta h, nehayat e nichly darjay ki baighairat aurat ho, aurat zaat ko b badnaam kea h isny apny wajood sy !! akhh thooo iski zaat pay
4. agar aaj se 40 saal pehley isi tarha ke banner pakarh kar mera jism meri marzi waala naara aapki amma ne maara hota to aap is duniya main ye tweet karney ke liye maujood hi na hoteen 😑😑😑

Generated output:
isky ghar mein toh pata nahi chal raha kis ny ungli kr di

Sample 2
------------------------------------------------------------
Sample index: 201
Generation seed: 301201
Demonstration seed: 305201

Demonstrations:
1. aisi or kis kis ki lund par uchel uchel kar moja lati ghar me.
2. jin ko hizab se nafrat he wo nangi ho k ghoome koi in pe thooke ga bhi nahi  aurat khoobsurat pure libas me lagti he mawazna karlen
3. shazaib apni baji ko b bejna han aurat march ma agr itne he zruri hai to
4. aurat ko islam nai galat lagta, ap log lagtay ho jo ye boltay hain k agar aurat ka rape hua to wo uski galtie usne sar par dupatta nai kiya us banday ki nahi wo bechara kesay control karay

Generated output:
saali jaldi aap ka dost hi banti ha

Sample 3
------------------------------------------------------------
Sample index: 202
Generation seed: 301202
Demonstration seed: 305202

Demonstrations:
1. lalchi aurat paisa dekhti hai aur khandani aurat sirf sehrat dekhti hai
2. agar aaj se 40 saal pehley isi tarha ke banner pakarh kar mera jism meri marzi waala naara aapki amma ne maara hota to aap is duniya main ye tweet karney ke liye maujood hi na hoteen 😑😑😑
3. ap ko mard banny ki acting pasand i? agr ni to hijra hi bany rahye sir ye mardo k kam hn hijro k ni.
4. aur jesi ghatia aurat ke mun se ye bat achi ni lagti. logon ko garam karnay wali machine.

Generated output:
tere maa ka yaar teri jaldi hi paida ho gaya tha aur tujhe teri ammi ne yeh soch diya tha

Sample 4
------------------------------------------------------------
Sample index: 203
Generation seed: 301203
Demonstration seed: 305203

Demonstrations:
1. ek randi larki ko itni pazeerai di hai. smjh se bahir hai
2. bc ghar wale bhi soch rahe honge yeh kya system paida ho gya sala lagta programing galat ho gayi.... sabsi badi confusion iske liye ladka dhundheyge yaa ladki😉
3. teri chut me sabhi bhaiyo ka lund reply de randi
4. ap ko mard banny ki acting pasand i? agr ni to hijra hi bany rahye sir ye mardo k kam hn hijro k ni.

Generated output:
tu jo nahin samajh sakti to tumhari maa ki choot me le jayega aur tera baap saala mc

Sample 5
------------------------------------------------------------
Sample index: 204
Generation seed: 301204
Demonstration seed: 305204

Demonstrations:
1. you are just girlfriend material no one wants wife like you. itna jism jo sirf admi apni bivi ka dekhta h  apka to sary jahan ne dekha h
2. original attitude boys ma hota ha aur fake girls ma
3. muslim countries ki leaderships na mard napunsak or hijra hain.. in mein koi dum nahi.. ye kuch nahi kr sakty.. jinnah ki rooh tarapti hogi.. jinnah ne kashmir par attack ka order diya tha..
4. tum jesi ghatia aurat ka kam hi ni hai media par.kisi kothhay pe ja aur ulta late ja ke.begherat

Generated output:
bhenchod tu yeh baat samjh rhi hai

In [100]:
# ============================================================
# INITIAL PROFANE SANITY CHECK
# 5 samples using original RUHSOLD demonstrations
# ============================================================

profane_test_samples = preview_generations(
    class_id=4,
    n_samples=5,
    start_index=300,
    show_demonstrations=True,
)

================================================================================
Target class: Profane
Demonstration source: Shortlisted authentic RUHSOLD Profane examples
Demonstration pool size: 40
================================================================================

Sample 1
------------------------------------------------------------
Sample index: 300
Generation seed: 401300
Demonstration seed: 405300

Demonstrations:
1. rt : asa kon ludo khelta hi bc ....😇
2. mere pas tum ho ny to puray saal ka rula dia bhenchod
3. tm jao ma ni ja rha, pehly he adhi zindagi saffr mein guzr gai bc meri.
4. bhenchod bht kutti haaalat huwe we he bhai

Generated output:
mera baap chutiya hai

Sample 2
------------------------------------------------------------
Sample index: 301
Generation seed: 401301
Demonstration seed: 405301

Demonstrations:
1. bhenchod mairi thand se phatt rahi hai
2. rona araha hai bhenchod why am i such a clown why am i so unimportant
3. why can’t i multitask???? i’m 22 fucking years old and i still dont know how to multitask bhenchod
4. rt : koi physics samjha de bhenchod,,,,

Generated output:
yeh kya lagta hai? abhi tak mein nahi pata ki jinko tujhe yaar bana raha hai wo chup nahi kr sakte hain

Sample 3
------------------------------------------------------------
Sample index: 302
Generation seed: 401302
Demonstration seed: 405302

Demonstrations:
1. rona araha hai bhenchod why am i such a clown why am i so unimportant
2. rt : yaar magar wifi bandh na karna, missile vissile daal do koi dikkat nahi, magar internet chahiye bc
3. rt : kisi ko bhulnay k liye ussay yaad karna parta hai. aur idhr bhenchod yaad hi ati rehti hai bus
4. bhenchod aaj sirf roneka mann kar raha hai

Generated output:
rt : mera kaam hai ke tereko pata chala jaye kya apne ghar mein kaun si bat hai

Sample 4
------------------------------------------------------------
Sample index: 303
Generation seed: 401303
Demonstration seed: 405303

Demonstrations:
1. bhenchod bht kutti haaalat huwe we he bhai
2. bhenchod kya hai ye sb
3. mere pas tum ho ny to puray saal ka rula dia bhenchod
4. bhenchod parhna hai. par dimaagh ijazat nahi deta. ajeeb chutiyapa hai ye.

Generated output:
tera baap hi tu ha bc

Sample 5
------------------------------------------------------------
Sample index: 304
Generation seed: 401304
Demonstration seed: 405304

Demonstrations:
1. rt : birthday wali feel hi nai arahi bhenchod
2. bc 40 rupees karaya kar diya hai is se acha to banda uber ya cream karwa laye 😏😏😏
3. fuck man. the pain is traveling. bhenchod ye naya e corridor khul gya hai.
4. bc bb khatm ho gya but i cant move on

Generated output:
bc 40 rupees karaya kar diya hai is se acha to banda uber ya cream karwa laye 😏😏😏

In [24]:
# ============================================================
# PREPARE ORIGINAL PROFANE CANDIDATES
# ============================================================

profane_candidates = (
    train_df[
        train_df["label"] == 4
    ][["text", "label"]]
    .drop_duplicates(subset=["text"])
    .reset_index(drop=True)
)

print(
    "Total unique Profane candidates:",
    len(profane_candidates)
)

Total unique Profane candidates: 410

In [25]:
# ============================================================
# BUILD SHORTLISTED PROFANE PROTOTYPE POOL
# ============================================================

PROFANE_PROTOTYPE_INDICES = [
    2, 3, 4, 5, 13, 28, 30, 32, 36, 38,
    39, 42, 48, 49, 53, 54, 60, 62, 68, 69,
    73, 74, 76, 77, 79, 85, 90, 91, 93, 96,
    98, 103, 104, 112, 119, 130, 137, 143,
    152, 153,
]

profane_prototype_pool = (
    profane_candidates
    .loc[
        PROFANE_PROTOTYPE_INDICES,
        ["text", "label"]
    ]
    .drop_duplicates(subset=["text"])
    .reset_index(drop=True)
)

print(
    "Profane prototype candidates:",
    len(profane_prototype_pool)
)

#display(profane_prototype_pool)

Profane prototype candidates: 40

In [26]:
# ============================================================
# PROFANE SANITY CHECK
# 5 samples using shortlisted prototype pool
# ============================================================

profane_test_samples = preview_generations(
    class_id=4,
    n_samples=5,
    start_index=300,
    show_demonstrations=True,
)

================================================================================
Target class: Profane
Demonstration source: Shortlisted authentic RUHSOLD Profane examples
Demonstration pool size: 40
================================================================================

Sample 1
------------------------------------------------------------
Sample index: 300
Generation seed: 401300
Demonstration seed: 405300

Demonstrations:
1. rt : asa kon ludo khelta hi bc ....😇
2. mere pas tum ho ny to puray saal ka rula dia bhenchod
3. tm jao ma ni ja rha, pehly he adhi zindagi saffr mein guzr gai bc meri.
4. bhenchod bht kutti haaalat huwe we he bhai

Generated output:
mera baap chutiya hai

Sample 2
------------------------------------------------------------
Sample index: 301
Generation seed: 401301
Demonstration seed: 405301

Demonstrations:
1. bhenchod mairi thand se phatt rahi hai
2. rona araha hai bhenchod why am i such a clown why am i so unimportant
3. why can’t i multitask???? i’m 22 fucking years old and i still dont know how to multitask bhenchod
4. rt : koi physics samjha de bhenchod,,,,

Generated output:
yeh kya lagta hai? abhi tak mein nahi pata ki jinko tujhe yaar bana raha hai wo chup nahi kr sakte hain

Sample 3
------------------------------------------------------------
Sample index: 302
Generation seed: 401302
Demonstration seed: 405302

Demonstrations:
1. rona araha hai bhenchod why am i such a clown why am i so unimportant
2. rt : yaar magar wifi bandh na karna, missile vissile daal do koi dikkat nahi, magar internet chahiye bc
3. rt : kisi ko bhulnay k liye ussay yaad karna parta hai. aur idhr bhenchod yaad hi ati rehti hai bus
4. bhenchod aaj sirf roneka mann kar raha hai

Generated output:
rt : mera kaam hai ke tereko pata chala jaye kya apne ghar mein kaun si bat hai

Sample 4
------------------------------------------------------------
Sample index: 303
Generation seed: 401303
Demonstration seed: 405303

Demonstrations:
1. bhenchod bht kutti haaalat huwe we he bhai
2. bhenchod kya hai ye sb
3. mere pas tum ho ny to puray saal ka rula dia bhenchod
4. bhenchod parhna hai. par dimaagh ijazat nahi deta. ajeeb chutiyapa hai ye.

Generated output:
tera baap hi tu ha bc

Sample 5
------------------------------------------------------------
Sample index: 304
Generation seed: 401304
Demonstration seed: 405304

Demonstrations:
1. rt : birthday wali feel hi nai arahi bhenchod
2. bc 40 rupees karaya kar diya hai is se acha to banda uber ya cream karwa laye 😏😏😏
3. fuck man. the pain is traveling. bhenchod ye naya e corridor khul gya hai.
4. bc bb khatm ho gya but i cant move on

Generated output:
bc 40 rupees karaya kar diya hai is se acha to banda uber ya cream karwa laye 😏😏😏

In [27]:
# ============================================================
# PROJECT PATH SETUP
# ============================================================

from pathlib import Path

PROJECT_ROOT = Path(
    "/home/jovyan/project work/data_analyssis"
)

print("Project root:")
print(PROJECT_ROOT)

print("\nExists:")
print(PROJECT_ROOT.exists())

Project root:
/home/jovyan/project work/data_analyssis

Exists:
True

In [107]:
# ============================================================
# GENERATE 100 PROFANE PILOT SAMPLES
# ============================================================

profane_pilot_df = generate_pilot_dataset(
    class_id=4,
    n_samples=100,
    start_index=0,
    save_every=10,
)

================================================================================
Generating pilot dataset
Class: Profane
Demonstration source: Shortlisted authentic RUHSOLD Profane examples
Demonstration pool size: 40
Samples: 100
Output: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/pilot/profane_raw_pilot_100.csv
================================================================================
Saved 10/100
Saved 20/100
Saved 30/100
Saved 40/100
Saved 50/100
Saved 60/100
Saved 70/100
Saved 80/100
Saved 90/100
Saved 100/100

Generation complete.
Shape: (100, 14)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/pilot/profane_raw_pilot_100.csv

In [108]:
# ============================================================
# GENERATE 100 SEXISM PILOT SAMPLES
# ============================================================

sexism_pilot_df = generate_pilot_dataset(
    class_id=3,
    n_samples=100,
    start_index=0,
    save_every=10,
)

================================================================================
Generating pilot dataset
Class: Sexism
Demonstration source: Shortlisted authentic RUHSOLD Sexism examples
Demonstration pool size: 40
Samples: 100
Output: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/pilot/sexism_raw_pilot_100.csv
================================================================================
Saved 10/100
Saved 20/100
Saved 30/100
Saved 40/100
Saved 50/100
Saved 60/100
Saved 70/100
Saved 80/100
Saved 90/100
Saved 100/100

Generation complete.
Shape: (100, 14)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/pilot/sexism_raw_pilot_100.csv

In [29]:
# ============================================================
# GENERATE ONE FINAL PRODUCTION BATCH
# ROUND-2 SAFE VERSION
# ============================================================

from pathlib import Path
import pandas as pd


def generate_production_batch(
    class_id,
    batch_number,
    start_index,
    batch_size=200,
    output_dir=None,
):
    """
    Generate one reproducible production batch
    for one RUHSOLD augmentation class.

    Supported classes:
        2 = Religious Hate
        3 = Sexism
        4 = Profane

    Parameters
    ----------
    class_id : int
        RUHSOLD target class ID.

    batch_number : int
        Batch number used in filenames and candidate IDs.

    start_index : int
        Starting sample index for deterministic seeds.

    batch_size : int
        Number of samples to generate.

    output_dir : Path or str, optional
        Directory where the generated batch will be saved.
        If None, FULL_OUTPUT_DIR is used.
    """

    # --------------------------------------------------------
    # Validate class
    # --------------------------------------------------------

    if class_id not in [2, 3, 4]:
        raise ValueError(
            "Production generation is only configured "
            "for classes 2, 3, and 4."
        )

    # --------------------------------------------------------
    # Select output directory
    # --------------------------------------------------------

    if output_dir is None:
        output_dir = FULL_OUTPUT_DIR

    output_dir = Path(
        output_dir
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    # --------------------------------------------------------
    # Select curated demonstration pool
    # --------------------------------------------------------

    if class_id == 2:

        demo_source_df = religious_prototype_pool

        demo_source_name = (
            "Shortlisted authentic RUHSOLD Religious Hate examples"
        )

    elif class_id == 3:

        demo_source_df = sexism_prototype_pool

        demo_source_name = (
            "Shortlisted authentic RUHSOLD Sexism examples"
        )

    elif class_id == 4:

        demo_source_df = profane_prototype_pool

        demo_source_name = (
            "Shortlisted authentic RUHSOLD Profane examples"
        )

    # --------------------------------------------------------
    # Build class-specific filename
    # --------------------------------------------------------

    class_file_name = (
        CLASS_METADATA[class_id]["label"]
        .lower()
        .replace("/", "_")
        .replace(" ", "_")
    )

    output_path = (
        output_dir
        / (
            f"{class_file_name}"
            f"_batch_{batch_number:03d}.csv"
        )
    )

    # --------------------------------------------------------
    # Prevent accidental overwrite
    # --------------------------------------------------------

    if output_path.exists():

        raise FileExistsError(
            f"Output file already exists:\n{output_path}\n\n"
            "Choose a new batch number or delete the file "
            "only if you intentionally want to regenerate it."
        )

    # --------------------------------------------------------
    # Display batch configuration
    # --------------------------------------------------------

    print("=" * 80)
    print("PRODUCTION GENERATION")
    print("=" * 80)

    print(
        "Class:",
        CLASS_METADATA[class_id]["label"]
    )

    print(
        "Batch number:",
        batch_number
    )

    print(
        "Batch size:",
        batch_size
    )

    print(
        "Start index:",
        start_index
    )

    print(
        "Demonstration source:",
        demo_source_name
    )

    print(
        "Demonstration pool size:",
        len(demo_source_df)
    )

    print(
        "Output directory:",
        output_dir
    )

    print(
        "Output file:",
        output_path
    )

    print("=" * 80)

    # --------------------------------------------------------
    # Generate batch
    # --------------------------------------------------------

    records = []

    for offset in range(
        batch_size
    ):

        sample_index = (
            start_index
            + offset
        )

        # ----------------------------------------------------
        # Deterministic generation seeds
        # ----------------------------------------------------

        generation_seed = (
            BASE_GENERATION_SEED
            + class_id * 100000
            + sample_index
        )

        demonstration_seed = (
            BASE_DEMONSTRATION_SEED
            + class_id * 100000
            + sample_index
        )

        # ----------------------------------------------------
        # Sample demonstrations
        # ----------------------------------------------------

        demonstrations = (
            sample_demonstrations(
                dataframe=demo_source_df,
                class_id=class_id,
                n_examples=N_DEMONSTRATIONS,
                random_state=demonstration_seed,
            )
        )

        # ----------------------------------------------------
        # Build few-shot prompt
        # ----------------------------------------------------

        messages = (
            build_few_shot_messages(
                class_id=class_id,
                demonstrations=demonstrations,
            )
        )

        # ----------------------------------------------------
        # Generate synthetic sample
        # ----------------------------------------------------

        generated_text = (
            generate_one(
                model=finetuned_model,
                messages=messages,
                seed=generation_seed,
            )
        )

        # ----------------------------------------------------
        # Unique production candidate ID
        # ----------------------------------------------------

        production_candidate_id = (
            f"class{class_id}_"
            f"batch{batch_number:03d}_"
            f"sample{sample_index:06d}"
        )

        # ----------------------------------------------------
        # Store generation record
        # ----------------------------------------------------

        records.append({
            "production_candidate_id":
                production_candidate_id,

            "batch_number":
                batch_number,

            "sample_index":
                sample_index,

            "class_id":
                class_id,

            "target_label":
                CLASS_METADATA[
                    class_id
                ]["label"],

            "generation_seed":
                generation_seed,

            "demonstration_seed":
                demonstration_seed,

            "prompt_version":
                PROMPT_VERSION,

            "prompting_strategy":
                "4-shot random authentic same-class",

            "demonstration_source":
                demo_source_name,

            "demonstration_pool_size":
                len(demo_source_df),

            "demo_1":
                demonstrations[0],

            "demo_2":
                demonstrations[1],

            "demo_3":
                demonstrations[2],

            "demo_4":
                demonstrations[3],

            "generated_text":
                generated_text,
        })

        # ----------------------------------------------------
        # Incremental save every 25 samples
        # ----------------------------------------------------

        if (
            (offset + 1) % 25 == 0
            or
            (offset + 1) == batch_size
        ):

            temporary_df = (
                pd.DataFrame(
                    records
                )
            )

            temporary_df.to_csv(
                output_path,
                index=False,
                encoding="utf-8"
            )

            print(
                f"Saved "
                f"{offset + 1}/{batch_size}"
            )

    # --------------------------------------------------------
    # Final dataframe
    # --------------------------------------------------------

    batch_df = (
        pd.DataFrame(
            records
        )
    )

    # --------------------------------------------------------
    # Final save
    # --------------------------------------------------------

    batch_df.to_csv(
        output_path,
        index=False,
        encoding="utf-8"
    )

    print("\nBatch generation complete.")

    print(
        "Shape:",
        batch_df.shape
    )

    print(
        "Saved to:",
        output_path
    )

    return batch_df

In [30]:
# ============================================================
# ROUND 2 OUTPUT DIRECTORY
# ============================================================

ROUND2_OUTPUT_DIR = (
    GENERATION_DIR
    / "full_round2"
)

ROUND2_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(
    "Round 2 output directory:"
)

print(
    ROUND2_OUTPUT_DIR
)

Round 2 output directory:
/home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2

In [46]:
# ============================================================
# RELIGIOUS HATE - ROUND 2
# Target: 900 additional raw generations
#
# Existing production:
# batches 1-5
# sample indices 10000-10999
#
# New production:
# batches 6-10
# sample indices 11000-11899
# ============================================================

# 4 batches x 200 = 800 samples
for batch_number in range(6, 10):

    start_index = (
        11000
        + (batch_number - 6) * 200
    )

    generate_production_batch(
        class_id=2,
        batch_number=batch_number,
        start_index=start_index,
        batch_size=200,
        output_dir=ROUND2_OUTPUT_DIR,
    )

# Final 100 samples
generate_production_batch(
    class_id=2,
    batch_number=10,
    start_index=11800,
    batch_size=100,
    output_dir=ROUND2_OUTPUT_DIR,
)

================================================================================
PRODUCTION GENERATION
================================================================================
Class: Religious Hate
Batch number: 6
Batch size: 200
Start index: 11000
Demonstration source: Shortlisted authentic RUHSOLD Religious Hate examples
Demonstration pool size: 118
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/religious_hate_batch_006.csv
================================================================================
Saved 25/200
Saved 50/200
Saved 75/200
Saved 100/200
Saved 125/200
Saved 150/200
Saved 175/200
Saved 200/200

Batch generation complete.
Shape: (200, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/religious_hate_batch_006.csv
================================================================================
PRODUCTION GENERATION
================================================================================
Class: Religious Hate
Batch number: 7
Batch size: 200
Start index: 11200
Demonstration source: Shortlisted authentic RUHSOLD Religious Hate examples
Demonstration pool size: 118
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/religious_hate_batch_007.csv
================================================================================
Saved 25/200
Saved 50/200
Saved 75/200
Saved 100/200
Saved 125/200
Saved 150/200
Saved 175/200
Saved 200/200

Batch generation complete.
Shape: (200, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/religious_hate_batch_007.csv
================================================================================
PRODUCTION GENERATION
================================================================================
Class: Religious Hate
Batch number: 8
Batch size: 200
Start index: 11400
Demonstration source: Shortlisted authentic RUHSOLD Religious Hate examples
Demonstration pool size: 118
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/religious_hate_batch_008.csv
================================================================================
Saved 25/200
Saved 50/200
Saved 75/200
Saved 100/200
Saved 125/200
Saved 150/200
Saved 175/200
Saved 200/200

Batch generation complete.
Shape: (200, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/religious_hate_batch_008.csv
================================================================================
PRODUCTION GENERATION
================================================================================
Class: Religious Hate
Batch number: 9
Batch size: 200
Start index: 11600
Demonstration source: Shortlisted authentic RUHSOLD Religious Hate examples
Demonstration pool size: 118
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/religious_hate_batch_009.csv
================================================================================
Saved 25/200
Saved 50/200
Saved 75/200
Saved 100/200
Saved 125/200
Saved 150/200
Saved 175/200
Saved 200/200

Batch generation complete.
Shape: (200, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/religious_hate_batch_009.csv
================================================================================
PRODUCTION GENERATION
================================================================================
Class: Religious Hate
Batch number: 10
Batch size: 100
Start index: 11800
Demonstration source: Shortlisted authentic RUHSOLD Religious Hate examples
Demonstration pool size: 118
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/religious_hate_batch_010.csv
================================================================================
Saved 25/100
Saved 50/100
Saved 75/100
Saved 100/100

Batch generation complete.
Shape: (100, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/religious_hate_batch_010.csv

,production_candidate_id,batch_number,sample_index,class_id,target_label,generation_seed,demonstration_seed,prompt_version,prompting_strategy,demonstration_source,demonstration_pool_size,demo_1,demo_2,demo_3,demo_4,generated_text
0,class2_batch010_sample011800,10,11800,2,Religious Hate,212800,216800,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,apne profile mein whats app me fb twitter mein is bahadur nojawaan ki pic lga kr islam se or nabi ke din se mhbt ka izhaar kren or itna share kren ek yahoodi apne na pak iradoon se baaz ajaye is shakhs ne quraan pak ki hifazahat mein ek bhtareen mhbt ka jita jagta sabot dia hai,o madadarchod: tum tu farigh ho aur yeh gashti tu waisay he sari raat jagti hay. o dallay o kanjar hum tu iran jatay hotay hain tu bata apni behan kitni baar mbs aur us kay wahabi sheikhon ko bhaijta hay.,abe mc mein bheju teri maa cow ka photo kat te hue bc. chod teri tarah andhbhakt nhi hu aur nhi illiterate.. go and drink cow piss.,yahoodi ko hitler ne chora or general ne in jaajoon ko chor k dhkya k ye kai hain.😂,tere ghar ka gharaq karwa diya tha jo tere ammi ko mara tha.
1,class2_batch010_sample011801,10,11801,2,Religious Hate,212801,216801,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,"rt : q. woh kaun si qome he,jis ne such bhi bola phr bhi jahnum mein jayegi? ans: yahoodi or nasara qome. shahid sindh",wow halala's product on fire as usual porkistaniðÿ˜‚ðÿ˜‚ðÿ˜‚,qadiyani pe lanat mirza khinzeer harami pe lanat.,get lost you kaafir.,abe teri maa chodta ha apni nikal gaya
2,class2_batch010_sample011802,10,11802,2,Religious Hate,212802,216802,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,ahmedi mirziee qadiyani hargiz kuleedi uhdu pe nhee janay chahien warna hmari agencies pe swalia nishan hey,jaa bhen k lory tum harrami ki nasal ho.. dewband maslak pe kutty ki tareh bhoonkty ho..,apne profile mein whats app me fb twitter mein is bahadur nojawaan ki pic lga kr islam se or nabi ke din se mhbt ka izhaar kren or itna share kren ek yahoodi apne na pak iradoon se baaz ajaye is shakhs ne quraan pak ki hifazahat mein ek bhtareen mhbt ka jita jagta sabot dia hai,"rt : q. woh kaun si qome he,jis ne such bhi bola phr bhi jahnum mein jayegi? ans: yahoodi or nasara qome. shahid sindh",qadyani kanjar aurat
3,class2_batch010_sample011803,10,11803,2,Religious Hate,212803,216803,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,abe bharwe tum hindu hi duniya k sub se bara atankwaz ho haramiyon bt krte ho hamare age tumhari country me hindu k elawa koi safe nhi he tumhari country ka name isi liye lynchistan he isi king all the world,uff pakiza muslim randi 😉😍,oeyy randdii k bachay ganddu hindu.. kyun jhoott baq raha hai gashti maa k ganndduu bachay. peshaab p k palnay wali qoum.,in beghairto israel yahodi khanzeer kai bacho nai kia kuch nahen kia hain lekhin alhamdulillah islam wahid deen jo mohabbat sikhati hain nakai nafrat aur ye sab sai tezi sai phelta huwa deen hain is liye inko jalan ho rahi hain aur har koshish kar bhe chukai hain aur kar bhe,tum logon ne apni amma ko khud kah diya tha ke tera baap hindu hai aur tu poore hindustan ki haramzadi beti hai
4,class2_batch010_sample011804,10,11804,2,Religious Hate,212804,216804,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,chhor bhen chod hrami hindu chhor esko😠😠😠,sali muslims randi. jihadi sali,plz sir hamy in say koi khtra nahi hamy is imran khan yahodi our kadiyanion say bachny pay gor karen pak army tayri azmat ko salam,"bilkul,itny lecture milny hain jese christmas or new year pe milty hain ,kya apko pata bhi hai k kaafir janwaro k haqq main dua bhi nahi krni chahye",oye kutiya ye jo dabang ho rha tha wo wahan se dabung hi nikal gaye 😂😂
5,class2_batch010_sample011805,10,11805,2,Religious Hate,212805,216805,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,q teri bhen ko chuda hy dewbandion ny ..harami ki nasal,pehle america jaiga ue begairaat musliman kehlwane kai laiq nh pehle he logh kehty h eske bary me ye yahoodi hai,#khuda ki qasam agar mey hota tu zinda nahe bach sakta ta muj sey ye beghairat kafir yahoodi.,phir kehty hum bhot badry #muslim hn aur #ashaq_e_rasool sawm hain lanat hai un sab #haramio py jinho ny bibi fatima zahra ko shahheed kia aur #haq khaya 🖐🏻😡🐕 aur lanat un sab py jo un #haramio ky hamdard hain,lanati imran chore zakat khore yahodi agent
6,class2_batch010_sample011806,10,11806,2,Religious Hate,212806,216806,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,"abbey halala ki paidaish, 5 baap ki aulaad. patthar baazi ke alawa kuchh kaam kara kabhi teri kaum ne ?","rt : q. woh kaun si qome he,jis ne such bhi bola phr bhi jahnum mein jayegi? ans: yahoodi or nasara qome. shahid sindh",tumri ma buhat hanzir hy jis ne tum jaise yahodi kafir rhandi hanzir aurat ko paida kiya,or mujhe un ladkiyo se utni hi nafrat hai jo mullo se shadi karti hai jitni kisi normal hindu ko😡 or mujhe hindu ladko se bhi itni hi nafrat hai jo muslim ladkiyo se shadi karte hai... dharam me koi milawat mujhe pasand nahi,"tum yahodi ho, humein kia pata, baki nizam tumare yahodi guruon ne bana diya hai"
7,class2_batch010_sample011807,10,11807,2,Religious Hate,212807,216807,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,yahodi agent qadyani chamcha,wow halala's product on fire as usual porkistaniðÿ˜‚ðÿ˜‚ðÿ˜‚,iran shia mulk ha or ye munafik log han,lul bukhari ye tum nahe tumaray yahoodi or hindu thuku bol rahay hain jin ko army sey bahot hi zeda takleef hai...🖕,i am ahmedi and i don't believe that islam is a religion
8,class2_batch010_sample011808,10,11808,2,Religious Hate,212808,216808,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,ye lode teri maa or bahan ke shohar hai or jyada bolega to de denge teri maa or bahan ko hum denge talaq or fir halala wow kya baat hai mullo wow lund chuss lo ðÿ˜œðÿ˜œðÿ˜œðÿ˜œ,"just the ten thousandth ""isolated"" instance of christian /jewish/hindu/ahmedi places of worship being attacked by crybabies who themselves can't handle some nutcase burning a book full of fiction stories.",pehle america jaiga ue begairaat musliman kehlwane kai laiq nh pehle he logh kehty h eske bary me ye yahoodi hai,oeyy randdii k bachay ganddu hindu.. kyun jhoott baq raha hai gashti maa k ganndduu bachay. peshaab p k palnay wali qoum.,islam ki sath to koi aur nahin hai
9,class2_batch010_sample011809,10,11809,2,Religious Hate,212809,216809,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,"path of cruelty , path of violence, path of halala , path of tripe talaq, path of marrying 6 years old aisha,path to discipline their wives by beating them,path of hurun,path of apostasy,path of punishable apostasy, path of beheading. what a pissful religion izlam is ðÿ‘",get lost you kaafir.,sirf momin aya to yahoodi kum nasal marny laggaye agr sawa crore momin agaye to sochen kya hoga?hamen jagna hoga,"abbey halala ki paidaish, 5 baap ki aulaad. patthar baazi ke alawa kuchh kaam kara kabhi teri kaum ne ?",apne aa gye hain bhenchod aurat ko choda raha tha to pata nhi kis ne
10,class2_batch010_sample011810,10,11810,2,Religious Hate,212810,216810,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,"afghanio ne tme hindu se bachaya,randi k aulaad tareekh paro tm wo ganda khoon ho,jo siko aour hindu ki rape se paida woe ho,tme kalima tho sikaya afghano ne,magar tmari gandi dna wai ranjeet sing wali a,randi k aulaad tm ne kah pana di,am pashtono ne di,apnay bio ko hera mandi",poocho hamarai imam sai kai quran mein kaha likha huwa hain aisai ye sirf yahodi khanzeer logo ki chaal hainmuslims ko badnaam karkai liye zara socho na tumharai hinduism ko badnaam kyun nahen kartai islam kai peechai kyun parai huwai hain zara dimagh ko khol kai socho,that's for foolish act and the ahmedi you highlighted they were equal to jews for us so alhmdurallah we save quran ! . and about hindus and christians its was a false news ! and if it is real then show me ! if you don't have anything then shut up and run !,iran shia mulk ha or ye munafik log han,apny ghr jao randi ka bacha
11,class2_batch010_sample011811,10,11811,2,Religious Hate,212811,216811,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,kafir yahodi kafir hindo same thinking,"just the ten thousandth ""isolated"" instance of christian /jewish/hindu/ahmedi places of worship being attacked by crybabies who themselves can't handle some nutcase burning a book full of fiction stories.",oy ahmdi kuty. tum log smjhty ho k is trah kr k hm awam ko pagl bnao gy?? beta bajwa ne tere jeso ko nanga nachana he sbr kr. kahi ni ja rha hmara army chief. tum logo ne agly 3 sal me ye duniya hi chor jani bajwa k dar se. ye army chief nahi pakistan ka muhafiz he.,bosdk yeh tumhare ghar me hota hai. saari k blouse me mote mote doodh dikhati firti hain tumhare dharam ki orate or hindu orat ko musalman ka l#nd aachaa lagta hai. yeh baat puri dunia janti hai,yar kutto abhi tak apke tweet per comment nai de raha koi..
12,class2_batch010_sample011812,10,11812,2,Religious Hate,212812,216812,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,chal na randi ! we have spiritual connection with supreme leader imam khamnae ! we have our hearts and souls for holy cities of najaf and karbala ! dont give a fck to wahabi chutiyas,that's for foolish act and the ahmedi you highlighted they were equal to jews for us so alhmdurallah we save quran ! . and about hindus and christians its was a false news ! and if it is real then show me ! if you don't have anything then shut up and run !,abe bharwe tum hindu hi duniya k sub se bara atankwaz ho haramiyon bt krte ho hamare age tumhari country me hindu k elawa koi safe nhi he tumhari country ka name isi liye lynchistan he isi king all the world,hey are fighting amongst each other. #bajwa is compromise candidate. thats only reason why he a ahmadiya is a coas.,shakal chutiya hai aurat ko nahi dikhane ki waja se choti si maa choot mar gaya tha ye
13,class2_batch010_sample011813,10,11813,2,Religious Hate,212813,216813,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,"ye manhoos hinduon ki diwali k chakkar mai har jaga ki aur quality kharab hogai, bharwe",but we have a firm belief now that qadiyani and ahmedi neither want muslims nor pakistanis to live in a harmony,is cult mein kisi boht hi pyare ko kho dene k baad uski qaber pe phool rakhna b jurm hai west mein qaberisat se phool chura k un ko sale kr k ahmdi chanda dia karte hain takey ragister se naam na kut jaye,"how did an ahmadiya get to the top in the army of sunnis, in the first place?","sahi yeh toh hua hai, mahira aur asim ka relationship dekhni padta hai"
14,class2_batch010_sample011814,10,11814,2,Religious Hate,212814,216814,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,pehle apni aurto ko halala se bachao ye bhi modi kar raha hai. agar sahi tum logo ka dna kiya jaye to pata nhi baap kon niklega,1 balatkari muslim 3 balatkari tera baap hindu h uske bare m kuch bol be,pehle america jaiga ue begairaat musliman kehlwane kai laiq nh pehle he logh kehty h eske bary me ye yahoodi hai,"ye manhoos hinduon ki diwali k chakkar mai har jaga ki aur quality kharab hogai, bharwe",haan tu teri maa ki phudi chodunga tu apne gandi behno ki chut jaldi maro
15,class2_batch010_sample011815,10,11815,2,Religious Hate,212815,216815,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,or mujhe un ladkiyo se utni hi nafrat hai jo mullo se shadi karti hai jitni kisi normal hindu ko😡 or mujhe hindu ladko se bhi itni hi nafrat hai jo muslim ladkiyo se shadi karte hai... dharam me koi milawat mujhe pasand nahi,tumhri maa kk chodu sale apni maa ko chod ke paida hone wale randi ki aulad sale apni behan ko biwi bana ke rkhne wale muhammad ki nazayaj aulad,sirf momin aya to yahoodi kum nasal marny laggaye agr sawa crore momin agaye to sochen kya hoga?hamen jagna hoga,#khuda ki qasam agar mey hota tu zinda nahe bach sakta ta muj sey ye beghairat kafir yahoodi.,teri maa ka yaar abhi tak tujhe pata nahi ki saali hamari baap beti ho
16,class2_batch010_sample011816,10,11816,2,Religious Hate,212816,216816,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,haha jaat dikha di bsdk antankbadi halala ki aulaad teri ammi ka halala hua tha phir to randi ke bacheðÿ¤£ðÿ¤£ðÿ˜…,"gau mutr peeyo tum log lodu awkat bna phir aake muh lag, randwa saala",yahoodi ko hitler ne chora or general ne in jaajoon ko chor k dhkya k ye kai hain.😂,hey are fighting amongst each other. #bajwa is compromise candidate. thats only reason why he a ahmadiya is a coas.,lanti munafiq niazi zardari say koi bat nahi kr rha wo bht baday khanzeer
17,class2_batch010_sample011817,10,11817,2,Religious Hate,212817,216817,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,"abbey halala ki paidaish, 5 baap ki aulaad. patthar baazi ke alawa kuchh kaam kara kabhi teri kaum ne ?",that's for foolish act and the ahmedi you highlighted they were equal to jews for us so alhmdurallah we save quran ! . and about hindus and christians its was a false news ! and if it is real then show me ! if you don't have anything then shut up and run !,chal na randi ! we have spiritual connection with supreme leader imam khamnae ! we have our hearts and souls for holy cities of najaf and karbala ! dont give a fck to wahabi chutiyas,q teri bhen ko chuda hy dewbandion ny ..harami ki nasal,tum nay bhej diya hai tere jaise logon ki gandu paidaish
18,class2_batch010_sample011818,10,11818,2,Religious Hate,212818,216818,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,please sell up you yahoodi bastards,#stopisraeliterror yahoodi mulk jisey israel ka naam diya gaya najaiz hai yahoodi sabse bada dahshatgard,"waise madarso mein bahut achhi taaleem di jaati hai tum jihadi hijdo ko, asar dikh rha hai yahan, khud toh khud ki bhen chodte hi ho aur dusro ko bhi bhenchod samajhte ho.",please all muslims come one page and unite insha allah yahoodi isreal finished all,qandeel baloch's father had announced reward if anyone killed her for honor. he got his son arrested who was her brother after she was murdered by family.
19,class2_batch010_sample011819,10,11819,2,Religious Hate,212819,216819,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,pislam me media ka estemal kerna haram hai halala ki paidais,tw kaafir tera peo kaafir tera pura khandaan kaafir ooo churry trump🐱🐱,tum log yahoodi ho kisi ko shuck nahi hona chaheye bus kafi hogae musalmanon ko aur dhoka na dou👹,"insaniyat ko bache rahne do, jis mazhab me janwar ka gala ret ke khushi banti hai, jis mazhab me soorma logo ko 72 virgin ladkiya baati jaati, jo duniya pe kabze ke sapne dekhta ho us mazhab se duuri banane me hi insaniyat ki bhalayi hai.",kashmir frosh ka yeh laga huwa hota ha jis ne apni maa beti ki izzat chod di ab humare yaha jinon ne unke sath izzat ka zamaana barbad kia
20,class2_batch010_sample011820,10,11820,2,Religious Hate,212820,216820,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,"insaniyat ko bache rahne do, jis mazhab me janwar ka gala ret ke khushi banti hai, jis mazhab me soorma logo ko 72 virgin ladkiya baati jaati, jo duniya pe kabze ke sapne dekhta ho us mazhab se duuri banane me hi insaniyat ki bhalayi hai.",jaa bhen k lory tum harrami ki nasal ho.. dewband maslak pe kutty ki tareh bhoonkty ho..,get lost you kaafir.,#stopisraeliterror yahoodi mulk jisey israel ka naam diya gaya najaiz hai yahoodi sabse bada dahshatgard,ye bhenchod charsi 😂
21,class2_batch010_sample011821,10,11821,2,Religious Hate,212821,216821,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,"gau mutr peeyo tum log lodu awkat bna phir aake muh lag, randwa saala",phir kehty hum bhot badry #muslim hn aur #ashaq_e_rasool sawm hain lanat hai un sab #haramio py jinho ny bibi fatima zahra ko shahheed kia aur #haq khaya 🖐🏻😡🐕 aur lanat un sab py jo un #haramio ky hamdard hain,sali muslims randi. jihadi sali,"hogai izzat? mera jism meri marzi jc ghaleez or ghatiya terminologies hamare muslim muashrey me dene ki koshish me aapki so-called,vahiyat or ikhlaq se giri support ko khud ne hi reject kardiya. apne yahoodi gods ko khush krne k liey kuch or karien",chal beghairt tere baap ka naam nhi pata
22,class2_batch010_sample011822,10,11822,2,Religious Hate,212822,216822,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,iran shia mulk ha or ye munafik log han,benchod randi islam,"obviously we muslims hate ahmedi's . 😡 we don't care whatever happens to them ! we just hate them. if their is oppression over other minorities in pakistan which is not usual alhamdolillah, then i condemn that.","rt : q. woh kaun si qome he,jis ne such bhi bola phr bhi jahnum mein jayegi? ans: yahoodi or nasara qome. shahid sindh",nawaz sharif khan gandu israaeli agent hai
23,class2_batch010_sample011823,10,11823,2,Religious Hate,212823,216823,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,"obviously we muslims hate ahmedi's . 😡 we don't care whatever happens to them ! we just hate them. if their is oppression over other minorities in pakistan which is not usual alhamdolillah, then i condemn that.",kaafir tujhe kuch nai malum,ye bat tum yahoodi ko bolo atankwadi tum ho jo musalman se nafrat ki aag me insaniyat ke sabse bade dushman yahoodi ko support karte ho ye log to face to face mara hai unlog chote bache ka upar bom feka kisi aurat ya admi bacha ko goli mar diya wi bhi waha ke civilian hi hai,no no ...... hindu na kah mujhe ........islam bura maan jayega .......kaafir kah kaafir...,kaafir tujhme khud hi nahin samjhte
24,class2_batch010_sample011824,10,11824,2,Religious Hate,212824,216824,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Religious Hate examples,118,tw kaafir tera peo kaafir tera pura khandaan kaafir ooo churry trump🐱🐱,bosdk yeh tumhare ghar me hota hai. saari k blouse me mote mote doodh dikhati firti hain tumhare dharam ki orate or hindu orat ko musalman ka l#nd aachaa lagta hai. yeh baat puri dunia janti hai,sirf momin aya to yahoodi kum nasal marny laggaye agr sawa crore momin agaye to sochen kya hoga?hamen jagna hoga,tumri ma buhat hanzir hy jis ne tum jaise yahodi kafir rhandi hanzir aurat ko paida kiya,abe ye yar apne nawaz ko na kro qadiyani agent keh raha hai ab ye bhi karte rha hai koi shak nahi

In [47]:
# ============================================================
# SEXISM - ROUND 2
# Target: 1300 additional raw generations
#
# Existing production:
# batches 1-4
# sample indices 20000-20799
#
# New production:
# batches 5-11
# sample indices 20800-22099
# ============================================================

# 6 batches x 200 = 1200 samples
for batch_number in range(5, 11):

    start_index = (
        20800
        + (batch_number - 5) * 200
    )

    generate_production_batch(
        class_id=3,
        batch_number=batch_number,
        start_index=start_index,
        batch_size=200,
        output_dir=ROUND2_OUTPUT_DIR,
    )

# Final 100 samples
generate_production_batch(
    class_id=3,
    batch_number=11,
    start_index=22000,
    batch_size=100,
    output_dir=ROUND2_OUTPUT_DIR,
)

================================================================================
PRODUCTION GENERATION
================================================================================
Class: Sexism
Batch number: 5
Batch size: 200
Start index: 20800
Demonstration source: Shortlisted authentic RUHSOLD Sexism examples
Demonstration pool size: 40
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_005.csv
================================================================================
Saved 25/200
Saved 50/200
Saved 75/200
Saved 100/200
Saved 125/200
Saved 150/200
Saved 175/200
Saved 200/200

Batch generation complete.
Shape: (200, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_005.csv
================================================================================
PRODUCTION GENERATION
================================================================================
Class: Sexism
Batch number: 6
Batch size: 200
Start index: 21000
Demonstration source: Shortlisted authentic RUHSOLD Sexism examples
Demonstration pool size: 40
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_006.csv
================================================================================
Saved 25/200
Saved 50/200
Saved 75/200
Saved 100/200
Saved 125/200
Saved 150/200
Saved 175/200
Saved 200/200

Batch generation complete.
Shape: (200, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_006.csv
================================================================================
PRODUCTION GENERATION
================================================================================
Class: Sexism
Batch number: 7
Batch size: 200
Start index: 21200
Demonstration source: Shortlisted authentic RUHSOLD Sexism examples
Demonstration pool size: 40
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_007.csv
================================================================================
Saved 25/200
Saved 50/200
Saved 75/200
Saved 100/200
Saved 125/200
Saved 150/200
Saved 175/200
Saved 200/200

Batch generation complete.
Shape: (200, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_007.csv
================================================================================
PRODUCTION GENERATION
================================================================================
Class: Sexism
Batch number: 8
Batch size: 200
Start index: 21400
Demonstration source: Shortlisted authentic RUHSOLD Sexism examples
Demonstration pool size: 40
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_008.csv
================================================================================
Saved 25/200
Saved 50/200
Saved 75/200
Saved 100/200
Saved 125/200
Saved 150/200
Saved 175/200
Saved 200/200

Batch generation complete.
Shape: (200, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_008.csv
================================================================================
PRODUCTION GENERATION
================================================================================
Class: Sexism
Batch number: 9
Batch size: 200
Start index: 21600
Demonstration source: Shortlisted authentic RUHSOLD Sexism examples
Demonstration pool size: 40
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_009.csv
================================================================================
Saved 25/200
Saved 50/200
Saved 75/200
Saved 100/200
Saved 125/200
Saved 150/200
Saved 175/200
Saved 200/200

Batch generation complete.
Shape: (200, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_009.csv
================================================================================
PRODUCTION GENERATION
================================================================================
Class: Sexism
Batch number: 10
Batch size: 200
Start index: 21800
Demonstration source: Shortlisted authentic RUHSOLD Sexism examples
Demonstration pool size: 40
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_010.csv
================================================================================
Saved 25/200
Saved 50/200
Saved 75/200
Saved 100/200
Saved 125/200
Saved 150/200
Saved 175/200
Saved 200/200

Batch generation complete.
Shape: (200, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_010.csv
================================================================================
PRODUCTION GENERATION
================================================================================
Class: Sexism
Batch number: 11
Batch size: 100
Start index: 22000
Demonstration source: Shortlisted authentic RUHSOLD Sexism examples
Demonstration pool size: 40
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_011.csv
================================================================================
Saved 25/100
Saved 50/100
Saved 75/100
Saved 100/100

Batch generation complete.
Shape: (100, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/sexism_batch_011.csv

,production_candidate_id,batch_number,sample_index,class_id,target_label,generation_seed,demonstration_seed,prompt_version,prompting_strategy,demonstration_source,demonstration_pool_size,demo_1,demo_2,demo_3,demo_4,generated_text
0,class3_batch011_sample022000,11,22000,3,Sexism,323000,327000,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,ap ko mard banny ki acting pasand i? agr ni to hijra hi bany rahye sir ye mardo k kam hn hijro k ni.,tu kyun ro rahe hai hijra? tera buddhe hijra to kamjor mard hai. uska kara nehi hota. 🤣🤣🤣🤣,#stopauratbarbadimarch aurat ghr k andr hi achi lgti he yu sarkon par nikalna kisi bhi aurat ki izzat par daag lga skta he,transgander madarchood hijra tu aik bara khoota ha haram zada,tu jis ny maulana ko bola tha wo teri maa behno ka phattar hoga...tujhy bhi aisa samjha hoga..
1,class3_batch011_sample022001,11,22001,3,Sexism,323001,327001,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,ek randi larki ko itni pazeerai di hai. smjh se bahir hai,randi kise kahte ha aap hi bata do? ye word ghatiya women ke liye hi use karta ha ab deepika ghatiya ha to randi hi bolenge na,r mazy k bat mra jism wo auratn krti hn jin pr thokta bh koi nae.,agar aaj se 40 saal pehley isi tarha ke banner pakarh kar mera jism meri marzi waala naara aapki amma ne maara hota to aap is duniya main ye tweet karney ke liye maujood hi na hoteen 😑😑😑,apke baare me sari dunia sharm khud rahi hai
2,class3_batch011_sample022002,11,22002,3,Sexism,323002,327002,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,#auratmarch2020 mera jism allah ki marzi.. allah ka to hukam ha tum char dewari me raho .. nd ya nikl k apni nimaish karna chahten,randi kise kahte ha aap hi bata do? ye word ghatiya women ke liye hi use karta ha ab deepika ghatiya ha to randi hi bolenge na,#stopauratbarbadimarch aurat ghr k andr hi achi lgti he yu sarkon par nikalna kisi bhi aurat ki izzat par daag lga skta he,ap ko mard banny ki acting pasand i? agr ni to hijra hi bany rahye sir ye mardo k kam hn hijro k ni.,teri maa chod di thi tu samjh le
3,class3_batch011_sample022003,11,22003,3,Sexism,323003,327003,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,#auratmarch2020 mera jism allah ki marzi.. allah ka to hukam ha tum char dewari me raho .. nd ya nikl k apni nimaish karna chahten,dhoka khane k baad oska aitbar uth jata haa sbsee or dosre mard mai b interest ni rehta...ku k aurat jism k ley ni chahti jbk mard jism k ley chahta😌🙂,tum jesi ghatia aurat ka kam hi ni hai media par.kisi kothhay pe ja aur ulta late ja ke.begherat,transgander madarchood hijra tu aik bara khoota ha haram zada,yar teri maa ko dekhna hoga na bsdk
4,class3_batch011_sample022004,11,22004,3,Sexism,323004,327004,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,we are supporting #islam and thank you #khalilurrahmanqamar for your beautiful comments against #gashti . agar ye #aurat hoti to na me aesi zuban use krta aur na koi gairatmand #admi use krta.,ek randi larki ko itni pazeerai di hai. smjh se bahir hai,muslim countries ki leaderships na mard napunsak or hijra hain.. in mein koi dum nahi.. ye kuch nahi kr sakty.. jinnah ki rooh tarapti hogi.. jinnah ne kashmir par attack ka order diya tha..,teri bhosdi or boobs me parda mat kar...logo ko dekne de.dhake hoge to kaise pata chalega ki tu hijra nehi hai. hijra kahi ki.,kisi randi ko pta chalna chaheye hai uski maa behn ka naam
5,class3_batch011_sample022005,11,22005,3,Sexism,323005,327005,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,teri bhosdi or boobs me parda mat kar...logo ko dekne de.dhake hoge to kaise pata chalega ki tu hijra nehi hai. hijra kahi ki.,transgander madarchood hijra tu aik bara khoota ha haram zada,jahiliyat ki v had hai ye apne ghar me slave ki tarh rahti hai aur bahar kutto jaise bhaunk rhi hai... shame on these ladies,bilo rani tumhari pehchan sirf or sirf hijra huna hai.. na mard,tere baap ka pakistani hai hijra
6,class3_batch011_sample022006,11,22006,3,Sexism,323006,327006,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,r mazy k bat mra jism wo auratn krti hn jin pr thokta bh koi nae.,#stopauratbarbadimarch aurat ghr k andr hi achi lgti he yu sarkon par nikalna kisi bhi aurat ki izzat par daag lga skta he,phir larky beard ky bagiar khusray q lgty hain wo bhi beard ky bagiar khubsurat lgny chahiye ?,teri bhosdi or boobs me parda mat kar...logo ko dekne de.dhake hoge to kaise pata chalega ki tu hijra nehi hai. hijra kahi ki.,tera baap dikha deta uske khaty mein kya hua
7,class3_batch011_sample022007,11,22007,3,Sexism,323007,327007,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,teri bhosdi or boobs me parda mat kar...logo ko dekne de.dhake hoge to kaise pata chalega ki tu hijra nehi hai. hijra kahi ki.,teri chut me sabhi bhaiyo ka lund reply de randi,original attitude boys ma hota ha aur fake girls ma,agar aaj se 40 saal pehley isi tarha ke banner pakarh kar mera jism meri marzi waala naara aapki amma ne maara hota to aap is duniya main ye tweet karney ke liye maujood hi na hoteen 😑😑😑,bharwe randi
8,class3_batch011_sample022008,11,22008,3,Sexism,323008,327008,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,agar aaj se 40 saal pehley isi tarha ke banner pakarh kar mera jism meri marzi waala naara aapki amma ne maara hota to aap is duniya main ye tweet karney ke liye maujood hi na hoteen 😑😑😑,teri chut me sabhi bhaiyo ka lund reply de randi,we are supporting #islam and thank you #khalilurrahmanqamar for your beautiful comments against #gashti . agar ye #aurat hoti to na me aesi zuban use krta aur na koi gairatmand #admi use krta.,jin ko hizab se nafrat he wo nangi ho k ghoome koi in pe thooke ga bhi nahi aurat khoobsurat pure libas me lagti he mawazna karlen,woh randi hy jo apni behno ki cheezain rakh rahy
9,class3_batch011_sample022009,11,22009,3,Sexism,323009,327009,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,phir larky beard ky bagiar khusray q lgty hain wo bhi beard ky bagiar khubsurat lgny chahiye ?,r mazy k bat mra jism wo auratn krti hn jin pr thokta bh koi nae.,you are just girlfriend material no one wants wife like you. itna jism jo sirf admi apni bivi ka dekhta h apka to sary jahan ne dekha h,shazaib apni baji ko b bejna han aurat march ma agr itne he zruri hai to,ye kia hua ha bhenchod
10,class3_batch011_sample022010,11,22010,3,Sexism,323010,327010,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,original attitude boys ma hota ha aur fake girls ma,teri bhosdi or boobs me parda mat kar...logo ko dekne de.dhake hoge to kaise pata chalega ki tu hijra nehi hai. hijra kahi ki.,#stopauratbarbadimarch aurat ghr k andr hi achi lgti he yu sarkon par nikalna kisi bhi aurat ki izzat par daag lga skta he,bilo rani tumhari pehchan sirf or sirf hijra huna hai.. na mard,jisko apnay dost ny hijra bol diya he woh hijra hy
11,class3_batch011_sample022011,11,22011,3,Sexism,323011,327011,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,apni behn ko bhejo gay na aurat march me??,randi kise kahte ha aap hi bata do? ye word ghatiya women ke liye hi use karta ha ab deepika ghatiya ha to randi hi bolenge na,#stopauratbarbadimarch who are you for arguing our tradition and islamic manners you bluddy 2 takay ki aurat .,"apko kehna chahye tha na mard hoon, na aurat hoo. main hijra hoon main hijra hoon, main parchi hoon, main defected hoon, main accidental chairman hoon. #joker420",tu yahan koi kaam nahi kar raha
12,class3_batch011_sample022012,11,22012,3,Sexism,323012,327012,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,original attitude boys ma hota ha aur fake girls ma,ap ko mard banny ki acting pasand i? agr ni to hijra hi bany rahye sir ye mardo k kam hn hijro k ni.,jahiliyat ki v had hai ye apne ghar me slave ki tarh rahti hai aur bahar kutto jaise bhaunk rhi hai... shame on these ladies,lalchi aurat paisa dekhti hai aur khandani aurat sirf sehrat dekhti hai,abhe tak naik kya baat ho gayi hai tu. abhi tk koi nhi kaha tha ke tera baap nhi hoga tu wo sach karke bolti hai. #captaincoolshukla
13,class3_batch011_sample022013,11,22013,3,Sexism,323013,327013,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,your leader is hijra that's why he is not living with his wife.,shazaib apni baji ko b bejna han aurat march ma agr itne he zruri hai to,acha tareka dhondha hai larkun ko ganda sabit karny ka but aesi neech harkat larkyan he kar sakti hain larky nahi.,tum jesi ghatia aurat ka kam hi ni hai media par.kisi kothhay pe ja aur ulta late ja ke.begherat,chutiya kanjar randi saali
14,class3_batch011_sample022014,11,22014,3,Sexism,323014,327014,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,shazaib apni baji ko b bejna han aurat march ma agr itne he zruri hai to,#stopauratbarbadimarch who are you for arguing our tradition and islamic manners you bluddy 2 takay ki aurat .,tu kyun ro rahe hai hijra? tera buddhe hijra to kamjor mard hai. uska kara nehi hota. 🤣🤣🤣🤣,r mazy k bat mra jism wo auratn krti hn jin pr thokta bh koi nae.,yehi hain isse gandu aurat
15,class3_batch011_sample022015,11,22015,3,Sexism,323015,327015,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,ap ko mard banny ki acting pasand i? agr ni to hijra hi bany rahye sir ye mardo k kam hn hijro k ni.,apni behn ko bhejo gay na aurat march me??,teri chut me sabhi bhaiyo ka lund reply de randi,"yeh wesy koi bht e zyda ounchi nasal ki randi niqli h wesy , mtlb i can't even imagine koi bughaz or paisy k pechay itna b girr skta h, nehayat e nichly darjay ki baighairat aurat ho, aurat zaat ko b badnaam kea h isny apny wajood sy !! akhh thooo iski zaat pay",bharwe tu hijra h teri maa chodu thaa
16,class3_batch011_sample022016,11,22016,3,Sexism,323016,327016,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,bilo rani tumhari pehchan sirf or sirf hijra huna hai.. na mard,jahiliyat ki v had hai ye apne ghar me slave ki tarh rahti hai aur bahar kutto jaise bhaunk rhi hai... shame on these ladies,"ab iska sara credit har anchor le rha h jb k rape, ki asal jad h hi media jo mera jism.meri marzi, hareem.shah , qandeel bloch , valentine day pe program krty hn phr rape hi hn gy",acha tareka dhondha hai larkun ko ganda sabit karny ka but aesi neech harkat larkyan he kar sakti hain larky nahi.,haha ye pakistan ke 50% ki auqaat thi😂😂😂
17,class3_batch011_sample022017,11,22017,3,Sexism,323017,327017,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,teri chut me sabhi bhaiyo ka lund reply de randi,jin ko hizab se nafrat he wo nangi ho k ghoome koi in pe thooke ga bhi nahi aurat khoobsurat pure libas me lagti he mawazna karlen,your leader is hijra that's why he is not living with his wife.,randi kise kahte ha aap hi bata do? ye word ghatiya women ke liye hi use karta ha ab deepika ghatiya ha to randi hi bolenge na,tere jaise randiyon ko kuch bhi bolega..kahan se nikl rahi ho ?
18,class3_batch011_sample022018,11,22018,3,Sexism,323018,327018,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,tere jaise randiyo ki chudai ke liye to ham mard hain yaha pe,acha tareka dhondha hai larkun ko ganda sabit karny ka but aesi neech harkat larkyan he kar sakti hain larky nahi.,ek randi larki ko itni pazeerai di hai. smjh se bahir hai,teri bhosdi or boobs me parda mat kar...logo ko dekne de.dhake hoge to kaise pata chalega ki tu hijra nehi hai. hijra kahi ki.,apnay maa baap ne bheje tha ab aapki kya shakl hai?
19,class3_batch011_sample022019,11,22019,3,Sexism,323019,327019,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,"yeh wesy koi bht e zyda ounchi nasal ki randi niqli h wesy , mtlb i can't even imagine koi bughaz or paisy k pechay itna b girr skta h, nehayat e nichly darjay ki baighairat aurat ho, aurat zaat ko b badnaam kea h isny apny wajood sy !! akhh thooo iski zaat pay",bc ghar wale bhi soch rahe honge yeh kya system paida ho gya sala lagta programing galat ho gayi.... sabsi badi confusion iske liye ladka dhundheyge yaa ladki😉,"apko kehna chahye tha na mard hoon, na aurat hoo. main hijra hoon main hijra hoon, main parchi hoon, main defected hoon, main accidental chairman hoon. #joker420",tu kyun ro rahe hai hijra? tera buddhe hijra to kamjor mard hai. uska kara nehi hota. 🤣🤣🤣🤣,wo bhenchod hijre ki jaldi kar raha hai
20,class3_batch011_sample022020,11,22020,3,Sexism,323020,327020,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,jin ko hizab se nafrat he wo nangi ho k ghoome koi in pe thooke ga bhi nahi aurat khoobsurat pure libas me lagti he mawazna karlen,tum jesi ghatia aurat ka kam hi ni hai media par.kisi kothhay pe ja aur ulta late ja ke.begherat,teri bhosdi or boobs me parda mat kar...logo ko dekne de.dhake hoge to kaise pata chalega ki tu hijra nehi hai. hijra kahi ki.,r mazy k bat mra jism wo auratn krti hn jin pr thokta bh koi nae.,tera baap hoga kisi chutiya ki bc
21,class3_batch011_sample022021,11,22021,3,Sexism,323021,327021,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,ek randi larki ko itni pazeerai di hai. smjh se bahir hai,acha tareka dhondha hai larkun ko ganda sabit karny ka but aesi neech harkat larkyan he kar sakti hain larky nahi.,apni behn ko bhejo gay na aurat march me??,jin ko hizab se nafrat he wo nangi ho k ghoome koi in pe thooke ga bhi nahi aurat khoobsurat pure libas me lagti he mawazna karlen,tum khanzeeri randiyon ki jaga mard ban liya ho
22,class3_batch011_sample022022,11,22022,3,Sexism,323022,327022,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,ek randi larki ko itni pazeerai di hai. smjh se bahir hai,transgander madarchood hijra tu aik bara khoota ha haram zada,agar aaj se 40 saal pehley isi tarha ke banner pakarh kar mera jism meri marzi waala naara aapki amma ne maara hota to aap is duniya main ye tweet karney ke liye maujood hi na hoteen 😑😑😑,"ab iska sara credit har anchor le rha h jb k rape, ki asal jad h hi media jo mera jism.meri marzi, hareem.shah , qandeel bloch , valentine day pe program krty hn phr rape hi hn gy",apni behno k chod do.
23,class3_batch011_sample022023,11,22023,3,Sexism,323023,327023,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,agar aaj se 40 saal pehley isi tarha ke banner pakarh kar mera jism meri marzi waala naara aapki amma ne maara hota to aap is duniya main ye tweet karney ke liye maujood hi na hoteen 😑😑😑,aaaahhhhhh bhenchod.....jese tere is mangalsutra ki sahi jagah tere gale me nai balki mere mote kaale lund pr he.... vese hi tujh jesi chudakkad kuttiya ki jagah kewal mere pairo k niche he saali.... chal inbox me aa.....,#auratmarch2020 mera jism allah ki marzi.. allah ka to hukam ha tum char dewari me raho .. nd ya nikl k apni nimaish karna chahten,your leader is hijra that's why he is not living with his wife.,abe bharwe bhenchodo aurat march kabhi na ho
24,class3_batch011_sample022024,11,22024,3,Sexism,323024,327024,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,bc ghar wale bhi soch rahe honge yeh kya system paida ho gya sala lagta programing galat ho gayi.... sabsi badi confusion iske liye ladka dhundheyge yaa ladki😉,your leader is hijra that's why he is not living with his wife.,#stopauratbarbadimarch aurat ghr k andr hi achi lgti he yu sarkon par nikalna kisi bhi aurat ki izzat par daag lga skta he,r mazy k bat mra jism wo auratn krti hn jin pr thokta bh koi nae.,tu mera jism meri marzi kutte ki nasal
25,class3_batch011_sample022025,11,22025,3,Sexism,323025,327025,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,#stopauratbarbadimarch who are you for arguing our tradition and islamic manners you bluddy 2 takay ki aurat .,ap ko mard banny ki acting pasand i? agr ni to hijra hi bany rahye sir ye mardo k kam hn hijro k ni.,r mazy k bat mra jism wo auratn krti hn jin pr thokta bh koi nae.,mard muhbt kr bhi ly tu aksar aurat he dhoka dy jati h usy 💔,tum nay shakl di hui ho yahan tera baap bhi nahi pata
26,class3_batch011_sample022026,11,22026,3,Sexism,323026,327026,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,lalchi aurat paisa dekhti hai aur khandani aurat sirf sehrat dekhti hai,aur jesi ghatia aurat ke mun se ye bat achi ni lagti. logon ko garam karnay wali machine.,acha tareka dhondha hai larkun ko ganda sabit karny ka but aesi neech harkat larkyan he kar sakti hain larky nahi.,we are supporting #islam and thank you #khalilurrahmanqamar for your beautiful comments against #gashti . agar ye #aurat hoti to na me aesi zuban use krta aur na koi gairatmand #admi use krta.,bharwe randi ki nasal
27,class3_batch011_sample022027,11,22027,3,Sexism,323027,327027,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,we are supporting #islam and thank you #khalilurrahmanqamar for your beautiful comments against #gashti . agar ye #aurat hoti to na me aesi zuban use krta aur na koi gairatmand #admi use krta.,tere jaise randiyo ki chudai ke liye to ham mard hain yaha pe,"yeh wesy koi bht e zyda ounchi nasal ki randi niqli h wesy , mtlb i can't even imagine koi bughaz or paisy k pechay itna b girr skta h, nehayat e nichly darjay ki baighairat aurat ho, aurat zaat ko b badnaam kea h isny apny wajood sy !! akhh thooo iski zaat pay",transgander madarchood hijra tu aik bara khoota ha haram zada,teri maa ka yaar bhenchod
28,class3_batch011_sample022028,11,22028,3,Sexism,323028,327028,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Sexism examples,40,"yeh wesy koi bht e zyda ounchi nasal ki randi niqli h wesy , mtlb i can't even imagine koi bughaz or paisy k pechay itna b girr skta h, nehayat e nichly darjay ki baighairat aurat ho, aurat zaat ko b badnaam kea h isny apny wajood sy !! akhh thooo iski zaat pay",acha tareka dhondha hai larkun ko ganda sabit karny ka but aesi neech harkat larkyan he kar sakti hain larky nahi.,transgander madarchood hijra tu aik bara khoota ha haram zada,"apko kehna chahye tha na mard hoon, na aurat hoo. main hijra hoon main hijra hoon, main parchi hoon, main defected hoon, main accidental chairman hoon. #joker420",abhi tak us ny 500+ tweets diye hain jis mein wo qandeel baloch k naam per bachpan ko le k bachpan se bachpan tarkeen he

In [48]:
# ============================================================
# PROFANE - ROUND 2
# Target: 450 additional raw generations
#
# Existing production:
# batches 1-3
# sample indices 30000-30599
#
# New production:
# batches 4-6
# sample indices 30600-31049
# ============================================================

# 2 batches x 200 = 400 samples
for batch_number in range(4, 6):

    start_index = (
        30600
        + (batch_number - 4) * 200
    )

    generate_production_batch(
        class_id=4,
        batch_number=batch_number,
        start_index=start_index,
        batch_size=200,
        output_dir=ROUND2_OUTPUT_DIR,
    )

# Final 50 samples
generate_production_batch(
    class_id=4,
    batch_number=6,
    start_index=31000,
    batch_size=50,
    output_dir=ROUND2_OUTPUT_DIR,
)

================================================================================
PRODUCTION GENERATION
================================================================================
Class: Profane
Batch number: 4
Batch size: 200
Start index: 30600
Demonstration source: Shortlisted authentic RUHSOLD Profane examples
Demonstration pool size: 40
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/profane_batch_004.csv
================================================================================
Saved 25/200
Saved 50/200
Saved 75/200
Saved 100/200
Saved 125/200
Saved 150/200
Saved 175/200
Saved 200/200

Batch generation complete.
Shape: (200, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/profane_batch_004.csv
================================================================================
PRODUCTION GENERATION
================================================================================
Class: Profane
Batch number: 5
Batch size: 200
Start index: 30800
Demonstration source: Shortlisted authentic RUHSOLD Profane examples
Demonstration pool size: 40
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/profane_batch_005.csv
================================================================================
Saved 25/200
Saved 50/200
Saved 75/200
Saved 100/200
Saved 125/200
Saved 150/200
Saved 175/200
Saved 200/200

Batch generation complete.
Shape: (200, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/profane_batch_005.csv
================================================================================
PRODUCTION GENERATION
================================================================================
Class: Profane
Batch number: 6
Batch size: 50
Start index: 31000
Demonstration source: Shortlisted authentic RUHSOLD Profane examples
Demonstration pool size: 40
Output directory: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2
Output file: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/profane_batch_006.csv
================================================================================
Saved 25/50
Saved 50/50

Batch generation complete.
Shape: (50, 16)
Saved to: /home/jovyan/project work/data_analyssis/fine tuning/outputs/synthetic_generation/full_round2/profane_batch_006.csv

,production_candidate_id,batch_number,sample_index,class_id,target_label,generation_seed,demonstration_seed,prompt_version,prompting_strategy,demonstration_source,demonstration_pool_size,demo_1,demo_2,demo_3,demo_4,generated_text
0,class4_batch006_sample031000,6,31000,4,Profane,432000,436000,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod mairi thand se phatt rahi hai,mera bhi yaar bhai...jindgi jhand ho gya hai bhenchodv 3 t20 me 300 rupya haar gye....,inn coaching vaalou ko kaise pta chal jaata hai mera result bhenchod.,naak bandd ho gya bc.,aby teri maa behn ka number dekh lete to acha nahi lagta
1,class4_batch006_sample031001,6,31001,4,Profane,432001,436001,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,my entire neighborhood is making weird sounds bhenchod shaddi hai kya,kyaaaa musibbaattt ha yr sara mood khraab kr diya ha bc,i hate ors bhenchod,bhenchod parhna hai. par dimaagh ijazat nahi deta. ajeeb chutiyapa hai ye.,bhenchod why do we even care about such things?
2,class4_batch006_sample031002,6,31002,4,Profane,432002,436002,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,rona araha hai bhenchod why am i such a clown why am i so unimportant,inn coaching vaalou ko kaise pta chal jaata hai mera result bhenchod.,bhenchod what a goal!,rt : asa kon ludo khelta hi bc ....😇,ye bhenchod
3,class4_batch006_sample031003,6,31003,4,Profane,432003,436003,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,dil sumbhal ja zra bhenchod,bhenchod bht kutti haaalat huwe we he bhai,rt : birthday wali feel hi nai arahi bhenchod,bhenchod kya hai ye sb,bc hn mein ne bhi bola tha maine
4,class4_batch006_sample031004,6,31004,4,Profane,432004,436004,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod kya hai ye sb,ajeeeeb bc 😒😂,main 5'8 ke sath bh chota lgta hn bc😶😑😑😑,bhenchod syllabus kuch aur..aur padhke kuch aur gaya.,bhenchod yeh sahi kia hai
5,class4_batch006_sample031005,6,31005,4,Profane,432005,436005,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,rt : asa kon ludo khelta hi bc ....😇,bhenchod aaj sirf roneka mann kar raha hai,kyaaaa musibbaattt ha yr sara mood khraab kr diya ha bc,"tm jao ma ni ja rha, pehly he adhi zindagi saffr mein guzr gai bc meri.",😂😂😂😂😂😂 ye chutiye ajeeb se pata nhi kis ny likha tha
6,class4_batch006_sample031006,6,31006,4,Profane,432006,436006,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod bht kutti haaalat huwe we he bhai,bhenchod aaj sirf roneka mann kar raha hai,why can’t i multitask???? i’m 22 fucking years old and i still dont know how to multitask bhenchod,"tm jao ma ni ja rha, pehly he adhi zindagi saffr mein guzr gai bc meri.",kbhi bhi bhenchod nahi bolta kabhi
7,class4_batch006_sample031007,6,31007,4,Profane,432007,436007,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod what a goal!,bhenchod kya hai ye sb,my entire neighborhood is making weird sounds bhenchod shaddi hai kya,code bhee saaf karna hai abheeee bc,mc chup krta hu aurat march ki baat kar raha hu😂
8,class4_batch006_sample031008,6,31008,4,Profane,432008,436008,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,dil sumbhal ja zra bhenchod,bhenchod aaj sirf roneka mann kar raha hai,mera bhi yaar bhai...jindgi jhand ho gya hai bhenchodv 3 t20 me 300 rupya haar gye....,bhenchod syllabus kuch aur..aur padhke kuch aur gaya.,rt : itna kia pta chl rha ha tu bhenchod
9,class4_batch006_sample031009,6,31009,4,Profane,432009,436009,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod mairi thand se phatt rahi hai,"rt : yaar magar wifi bandh na karna, missile vissile daal do koi dikkat nahi, magar internet chahiye bc",slept for only 4 hours last night bc match daikhty daikhty girny wala hua wa hun,bauhat sardi hai bc,"rt : abhi tk match mein bhi 70% runs change ho rahe hain, bc"
10,class4_batch006_sample031010,6,31010,4,Profane,432010,436010,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,rt : fariha without fa is riha and riha kerdo koi bhenchod is zindagi se,rt : kisi ko bhulnay k liye ussay yaad karna parta hai. aur idhr bhenchod yaad hi ati rehti hai bus,"rt : koi physics samjha de bhenchod,,,,",inn coaching vaalou ko kaise pta chal jaata hai mera result bhenchod.,kya bhenchod ye kaunsi baat hai
11,class4_batch006_sample031011,6,31011,4,Profane,432011,436011,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,ajeeeeb bc 😒😂,bauhat sardi hai bc,rt : bhenchod graph paper pe eraser use karo toh graph paper hi gayab ho jaata hai,why can’t i multitask???? i’m 22 fucking years old and i still dont know how to multitask bhenchod,bhenchod charsi
12,class4_batch006_sample031012,6,31012,4,Profane,432012,436012,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,"tm jao ma ni ja rha, pehly he adhi zindagi saffr mein guzr gai bc meri.",bhenchod what a goal!,rona araha hai bhenchod why am i such a clown why am i so unimportant,bhenchod aaj sirf roneka mann kar raha hai,bhenchod ye kya hi baat hai
13,class4_batch006_sample031013,6,31013,4,Profane,432013,436013,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod what a goal!,inn coaching vaalou ko kaise pta chal jaata hai mera result bhenchod.,"tm jao ma ni ja rha, pehly he adhi zindagi saffr mein guzr gai bc meri.",rt : fariha without fa is riha and riha kerdo koi bhenchod is zindagi se,bhenchod tum logon ko kya pta tha ke tere baap ne ye kehte the?
14,class4_batch006_sample031014,6,31014,4,Profane,432014,436014,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,naak bandd ho gya bc.,inn coaching vaalou ko kaise pta chal jaata hai mera result bhenchod.,nazar lag gayi bhenchod fuck this i knew it would never last,bhenchod what a goal!,ye bhenchod tere jaisay bachay tu apni maa ki goli maar
15,class4_batch006_sample031015,6,31015,4,Profane,432015,436015,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bauhat sardi hai bc,"tm jao ma ni ja rha, pehly he adhi zindagi saffr mein guzr gai bc meri.",bhenchod aaj sirf roneka mann kar raha hai,my entire neighborhood is making weird sounds bhenchod shaddi hai kya,randi rona krna chahye tha
16,class4_batch006_sample031016,6,31016,4,Profane,432016,436016,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,"rt : yaar magar wifi bandh na karna, missile vissile daal do koi dikkat nahi, magar internet chahiye bc",bc bb khatm ho gya but i cant move on,code bhee saaf karna hai abheeee bc,rona araha hai bhenchod why am i such a clown why am i so unimportant,ye bc sacha ha
17,class4_batch006_sample031017,6,31017,4,Profane,432017,436017,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod kahan phass gaya hoon,rt : bhenchod graph paper pe eraser use karo toh graph paper hi gayab ho jaata hai,code bhee saaf karna hai abheeee bc,my entire neighborhood is making weird sounds bhenchod shaddi hai kya,bhenchod paisa le rha tha abhi
18,class4_batch006_sample031018,6,31018,4,Profane,432018,436018,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,rt : birthday wali feel hi nai arahi bhenchod,bhenchod kahan phass gaya hoon,dil sumbhal ja zra bhenchod,kyaaaa musibbaattt ha yr sara mood khraab kr diya ha bc,mn bhi thk hi ho rha hu.. 😂😂
19,class4_batch006_sample031019,6,31019,4,Profane,432019,436019,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod mairi thand se phatt rahi hai,rt : kisi ko bhulnay k liye ussay yaad karna parta hai. aur idhr bhenchod yaad hi ati rehti hai bus,"rt : koi physics samjha de bhenchod,,,,",bhenchod aaj sirf roneka mann kar raha hai,"rt : bc jb main ne bhi dm kia tha tab me ne bola tha ""mai chup krta hun"""
20,class4_batch006_sample031020,6,31020,4,Profane,432020,436020,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,naak bandd ho gya bc.,2 years ago i asked my father for my own car. so he said “hbl car loan se lelo” bc itni khajal khawari keh tang akar i bought used honda civic. and mine is way better than new honda city. or sashky apny,"tm jao ma ni ja rha, pehly he adhi zindagi saffr mein guzr gai bc meri.",rt : birthday wali feel hi nai arahi bhenchod,"rt : this is when you start realising why your girlfriend was so obsessed with you. bc she's just like ""mere baap ki chut"""
21,class4_batch006_sample031021,6,31021,4,Profane,432021,436021,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,mera bhi yaar bhai...jindgi jhand ho gya hai bhenchodv 3 t20 me 300 rupya haar gye....,"tm jao ma ni ja rha, pehly he adhi zindagi saffr mein guzr gai bc meri.",bhenchod exams uff,"rt : yaar magar wifi bandh na karna, missile vissile daal do koi dikkat nahi, magar internet chahiye bc","bhenchod ye paisa abhi tak hi nahi dekha, aur ekdum baar bar kaha, 😂"
22,class4_batch006_sample031022,6,31022,4,Profane,432022,436022,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod bht kutti haaalat huwe we he bhai,mere pas tum ho ny to puray saal ka rula dia bhenchod,bc 40 rupees karaya kar diya hai is se acha to banda uber ya cream karwa laye 😏😏😏,bhenchod exams uff,bhenchod apko tere jaisi shakl dekhna to mujhe hi chod diya
23,class4_batch006_sample031023,6,31023,4,Profane,432023,436023,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,ajeeeeb bc 😒😂,i hate ors bhenchod,my entire neighborhood is making weird sounds bhenchod shaddi hai kya,neend aa rhi h bc main sone jaa rhi hu 😂,tera baap nikla tha jo ab teri maa ko chodta hai
24,class4_batch006_sample031024,6,31024,4,Profane,432024,436024,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,rt : birthday wali feel hi nai arahi bhenchod,2 years ago i asked my father for my own car. so he said “hbl car loan se lelo” bc itni khajal khawari keh tang akar i bought used honda civic. and mine is way better than new honda city. or sashky apny,nazar lag gayi bhenchod fuck this i knew it would never last,inn coaching vaalou ko kaise pta chal jaata hai mera result bhenchod.,rt : bhenchod jab tak tu na mila tab tak abhi abhi tere liye yaad rahna hota
25,class4_batch006_sample031025,6,31025,4,Profane,432025,436025,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,mera bhi yaar bhai...jindgi jhand ho gya hai bhenchodv 3 t20 me 300 rupya haar gye....,"rt : yaar magar wifi bandh na karna, missile vissile daal do koi dikkat nahi, magar internet chahiye bc",rt : birthday wali feel hi nai arahi bhenchod,bhenchod kahan phass gaya hoon,rt : ye pakistan ki tarha hai bhenchod
26,class4_batch006_sample031026,6,31026,4,Profane,432026,436026,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,i should've a bhenchod counter which will count the amount of times i've sad bhenchod,naak bandd ho gya bc.,kyaaaa musibbaattt ha yr sara mood khraab kr diya ha bc,bc bb khatm ho gya but i cant move on,bc meri maa chod do
27,class4_batch006_sample031027,6,31027,4,Profane,432027,436027,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod exams uff,why can’t i multitask???? i’m 22 fucking years old and i still dont know how to multitask bhenchod,bhenchod bht kutti haaalat huwe we he bhai,neend aa rhi h bc main sone jaa rhi hu 😂,abi tak apne charsi ko mily ga na 😑
28,class4_batch006_sample031028,6,31028,4,Profane,432028,436028,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod what a goal!,bauhat sardi hai bc,ajeeeeb bc 😒😂,rona araha hai bhenchod why am i such a clown why am i so unimportant,ye chutiya hai kya
29,class4_batch006_sample031029,6,31029,4,Profane,432029,436029,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,mere pas tum ho ny to puray saal ka rula dia bhenchod,my entire neighborhood is making weird sounds bhenchod shaddi hai kya,bhenchod parhna hai. par dimaagh ijazat nahi deta. ajeeb chutiyapa hai ye.,bhenchod exams uff,bhenchod nawaz shareef ko sari pakistan ko maaf kar dein
30,class4_batch006_sample031030,6,31030,4,Profane,432030,436030,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod exams uff,pubg lover hath toota howa hai phir b pubg nhai chorni bc😂😂😂,rt : birthday wali feel hi nai arahi bhenchod,main 5'8 ke sath bh chota lgta hn bc😶😑😑😑,abhe bhenchod jab koi kuch nahin kr skta tbh
31,class4_batch006_sample031031,6,31031,4,Profane,432031,436031,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,i should've a bhenchod counter which will count the amount of times i've sad bhenchod,bauhat sardi hai bc,2 years ago i asked my father for my own car. so he said “hbl car loan se lelo” bc itni khajal khawari keh tang akar i bought used honda civic. and mine is way better than new honda city. or sashky apny,bhenchod mairi thand se phatt rahi hai,bhenchod ye kaunsi cheez hai
32,class4_batch006_sample031032,6,31032,4,Profane,432032,436032,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bauhat sardi hai bc,pubg lover hath toota howa hai phir b pubg nhai chorni bc😂😂😂,bhenchod aaj sirf roneka mann kar raha hai,bhenchod bht kutti haaalat huwe we he bhai,randdi ki nasal
33,class4_batch006_sample031033,6,31033,4,Profane,432033,436033,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bauhat sardi hai bc,bhenchod kahan phass gaya hoon,bhenchod mairi thand se phatt rahi hai,"rt : koi physics samjha de bhenchod,,,,",maira jism meri marzi tere jism tujhe tera marzi
34,class4_batch006_sample031034,6,31034,4,Profane,432034,436034,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,"rt : yaar magar wifi bandh na karna, missile vissile daal do koi dikkat nahi, magar internet chahiye bc",rt : birthday wali feel hi nai arahi bhenchod,bc 40 rupees karaya kar diya hai is se acha to banda uber ya cream karwa laye 😏😏😏,pubg lover hath toota howa hai phir b pubg nhai chorni bc😂😂😂,ye jhootha aurat hai.. 🙄🙄
35,class4_batch006_sample031035,6,31035,4,Profane,432035,436035,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,inn coaching vaalou ko kaise pta chal jaata hai mera result bhenchod.,kyaaaa musibbaattt ha yr sara mood khraab kr diya ha bc,bhenchod kya hai ye sb,bhenchod syllabus kuch aur..aur padhke kuch aur gaya.,bhenchod bachpan ka memory nhi hota
36,class4_batch006_sample031036,6,31036,4,Profane,432036,436036,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,rt : bhenchod graph paper pe eraser use karo toh graph paper hi gayab ho jaata hai,neend aa rhi h bc main sone jaa rhi hu 😂,"rt : yaar magar wifi bandh na karna, missile vissile daal do koi dikkat nahi, magar internet chahiye bc",inn coaching vaalou ko kaise pta chal jaata hai mera result bhenchod.,"tere baap ki bat kar raha tha yeh, gand mein dard hai"
37,class4_batch006_sample031037,6,31037,4,Profane,432037,436037,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod parhna hai. par dimaagh ijazat nahi deta. ajeeb chutiyapa hai ye.,ajeeeeb bc 😒😂,bhenchod aaj sirf roneka mann kar raha hai,bhenchod bht kutti haaalat huwe we he bhai,"rt : ""jaa jaa ke na"" ""bhenchod aise hi bolte rehte hain"""
38,class4_batch006_sample031038,6,31038,4,Profane,432038,436038,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod bht kutti haaalat huwe we he bhai,2 years ago i asked my father for my own car. so he said “hbl car loan se lelo” bc itni khajal khawari keh tang akar i bought used honda civic. and mine is way better than new honda city. or sashky apny,"rt : koi physics samjha de bhenchod,,,,",bc bb khatm ho gya but i cant move on,jab tak tu lgta nahee hota to tera baap koi dikha deta nahi.
39,class4_batch006_sample031039,6,31039,4,Profane,432039,436039,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bauhat sardi hai bc,nazar lag gayi bhenchod fuck this i knew it would never last,bhenchod kahan phass gaya hoon,why can’t i multitask???? i’m 22 fucking years old and i still dont know how to multitask bhenchod,rt : yehi bhenchod tumhari larki ke bare mein bat kar rahe ho
40,class4_batch006_sample031040,6,31040,4,Profane,432040,436040,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,dil sumbhal ja zra bhenchod,bhenchod bht kutti haaalat huwe we he bhai,rt : bhenchod graph paper pe eraser use karo toh graph paper hi gayab ho jaata hai,bhenchod mairi thand se phatt rahi hai,rt : bhenchod jisko 75000 ka bill dekh liya jati hai woh abhi tak charsi ki paidaish nhi hui
41,class4_batch006_sample031041,6,31041,4,Profane,432041,436041,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,naak bandd ho gya bc.,bc bb khatm ho gya but i cant move on,rt : birthday wali feel hi nai arahi bhenchod,my entire neighborhood is making weird sounds bhenchod shaddi hai kya,bhai apki dost ko follow kro bhenchod
42,class4_batch006_sample031042,6,31042,4,Profane,432042,436042,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,bhenchod syllabus kuch aur..aur padhke kuch aur gaya.,"rt : koi physics samjha de bhenchod,,,,",ajeeeeb bc 😒😂,bhenchod what a goal!,rt : charsi tera baap hai.. 🤣
43,class4_batch006_sample031043,6,31043,4,Profane,432043,436043,v3_original_demo_boundary_prompt,4-shot random authentic same-class,Shortlisted authentic RUHSOLD Profane examples,40,ajeeeeb bc 😒😂,rona araha hai bhenchod why am i such a clown why am i so unimportant,naak bandd ho gya bc.,rt : asa kon ludo khelta hi bc ....😇,"rt : i'm done with people who tell me ""hmmm wese kabhi socha tha na"""

In [49]:
# ============================================================
# VERIFY ROUND 2 GENERATION FILES
# ============================================================

from pathlib import Path
import pandas as pd

ROUND2_OUTPUT_DIR = (
    GENERATION_DIR
    / "full_round2"
)

round2_files = sorted(
    ROUND2_OUTPUT_DIR.glob("*.csv")
)

print(
    "Round 2 files found:",
    len(round2_files)
)

for path in round2_files:
    df = pd.read_csv(path)

    print(
        path.name,
        "->",
        len(df)
    )

Round 2 files found: 15
profane_batch_004.csv -> 200
profane_batch_005.csv -> 200
profane_batch_006.csv -> 50
religious_hate_batch_006.csv -> 200
religious_hate_batch_007.csv -> 200
religious_hate_batch_008.csv -> 200
religious_hate_batch_009.csv -> 200
religious_hate_batch_010.csv -> 100
sexism_batch_005.csv -> 200
sexism_batch_006.csv -> 200
sexism_batch_007.csv -> 200
sexism_batch_008.csv -> 200
sexism_batch_009.csv -> 200
sexism_batch_010.csv -> 200
sexism_batch_011.csv -> 100

In [50]:
# ============================================================
# COMBINE ROUND 2 RAW GENERATIONS
# ============================================================

round2_frames = []

for path in round2_files:

    df = pd.read_csv(path)

    df["source_batch_file"] = (
        path.name
    )

    round2_frames.append(
        df
    )


round2_raw_df = pd.concat(
    round2_frames,
    ignore_index=True,
)


print(
    "Combined Round 2 shape:",
    round2_raw_df.shape
)

print(
    "\nClass distribution:"
)

display(
    round2_raw_df[
        "target_label"
    ]
    .value_counts()
    .rename_axis("Class")
    .reset_index(name="Count")
)


print(
    "\nDuplicate candidate IDs:",
    round2_raw_df[
        "production_candidate_id"
    ]
    .duplicated()
    .sum()
)

print(
    "Missing generated texts:",
    round2_raw_df[
        "generated_text"
    ]
    .isna()
    .sum()
)

print(
    "Exact duplicate generated texts:",
    round2_raw_df[
        "generated_text"
    ]
    .duplicated()
    .sum()
)

Combined Round 2 shape: (2650, 17)

Class distribution:

            Class  Count
0          Sexism   1300
1  Religious Hate    900
2         Profane    450

Duplicate candidate IDs: 0
Missing generated texts: 0
Exact duplicate generated texts: 30